/**
 * 國小社會 10 堂（elementary-social-add.ts）
 *
 * 課程表來自 docs/onion-200-plan.md →「社會 10 堂」（id: el-soc-*）。
 * 每堂課 9 幀分鏡（步驟標籤、字幕、action、prop、duration，至少 3 幀有 ask）
 * ＋ 6 題闖關（含 2 級提示與詳解）＋ 4 條 takeaways。
 * 圖解依各課核心概念選用 flow（演變、制度流程）、text（定義與對照）、
 * bars（人次／花費比較）、cycle（節慶循環）。
 */
import type { OnionLesson } from "@/game/onionAcademyLessons";

const EL_SOC_FAMILY: OnionLesson = {
  id: "el-soc-family",
  title: "家庭與我",
  subject: "社會",
  topic: "家庭與我",
  grade: "三上",
  stages: ["國小"],
  desc: "家裡有哪些人？大家怎麼分工？洋蔥帶你認識家庭成員和家庭樹。",
  takeaways: [
    "家庭成員有祖輩、父母、子女，組成方式可能不同",
    "家人分工是為了互相幫忙、分擔家事",
    "家庭樹能清楚呈現我和長輩的親屬關係",
    "家庭組成千百種樣貌，不論小家庭、大家庭或其他組成，每個家都值得尊重與珍惜",
  ],
  frames: [
    { id: 1, step: "步驟 1：想想家裡的分工", caption: "你有沒有想過，家裡的人各自在忙什麼？為什麼家事要分開做，而不是一個人全包？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：列出常見家人角色", caption: "我們一起來看，家裡常見的成員有爺爺奶奶、爸爸媽媽，還有我和兄弟姐妹。", action: "point", prop: { kind: "flow", steps: ["爺爺奶奶", "爸爸媽媽", "我", "兄弟姐妹"], active: 1 }, duration: 3600 },
    { id: 3, step: "步驟 3：我也能分擔家事", caption: "其實我也能盡一份力喔！像整理自己的書包、倒垃圾，都是我可以分擔的家事。", action: "point", prop: { kind: "flow", steps: ["整理書包", "倒垃圾", "洗碗筷"], active: 1 }, duration: 3600, ask: { prompt: "下列哪一項是你可以在家分擔的家事？", options: ["整理自己的書包", "家事是大人的事，小孩不用碰", "我只要唸好書，家事不用管", "等長輩全部做好再說就好"], answer: 0, hint: "想想你自己的房間，本來該由誰負責整理？" } },
    { id: 4, step: "步驟 4：了解家人分工", caption: "記得哦，每個家人負擔不同：有人上班賺錢、有人操持家務，大家互相幫忙。", action: "think", prop: { kind: "flow", steps: ["爸爸上班賺錢", "媽媽做家事", "我整理書包", "一起做家事"], active: 2 }, duration: 3600, ask: { prompt: "家人分工最主要的原因是什麼？", options: ["家事本來就該媽媽一個人做", "為了互相幫忙、分擔工作", "分工就是把工作推給別人", "小孩還小，長大才需要分家事"], answer: 1, hint: "想想如果全部家事都丟給一個人做，會怎麼樣？" } },
    { id: 5, step: "步驟 5：畫出一張家庭樹", caption: "我們可以畫一張家庭樹，從『我』往上找，就能看到爸爸媽媽和祖父母。", action: "point", prop: { kind: "text", text: "家庭樹：我 → 父母 → 祖父母", sub: "從我往上推認識長輩", tone: "ok" }, duration: 3600 },
    { id: 6, step: "步驟 6：比較不同家庭組成", caption: "你有沒有發現，有的家只有父母和我，叫小家庭；也有和長輩同住的大家庭。", action: "jump", prop: { kind: "text", text: "小家庭：父母＋子女", sub: "大家庭：同住長輩親戚", tone: "ok" }, duration: 3600, ask: { prompt: "小美家只有爸爸、媽媽和她，這是哪一種家庭？", options: ["小家庭", "大家庭", "單親家庭", "隔代教養家庭"], answer: 0, hint: "小家庭通常是父母和子女同住。" } },
    { id: 7, step: "步驟 7：感受家人的支持", caption: "你想想看，家人照顧我們的生活、陪我們長大，也讓我們心裡很踏實。", action: "walk", prop: { kind: "flow", steps: ["照顧生活", "陪伴成長", "給安全感"], active: 0 }, duration: 3600 },
    { id: 8, step: "步驟 8：每個家都獨一無二", caption: "記得哦，家庭有千百種樣貌，不論哪一種組成，每個家都值得尊重與珍惜。", action: "walk", prop: { kind: "text", text: "家庭百百款，都值得珍惜", sub: "不用和別人比較", tone: "ok" }, duration: 3400 },
    { id: 9, step: "步驟 9：整理家庭重點", caption: "我們一起記住：家人有分工、家庭樹清楚、彼此關心。預備好了，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-family-1", prompt: "下列哪一組都屬於家庭成員？", options: ["常照顧我的導師", "早餐店的老闆娘", "爸爸、媽媽、我", "社區管理員"], answer: 2, hints: ["家人是和你同住、有親屬關係的人", "爸爸媽媽和我是家人"], explanation: "爸爸、媽媽和自己是有親屬關係、同住的家庭成員；導師、老闆娘是家庭以外的人。" },
    { id: "el-soc-family-2", prompt: "家人為什麼要分工？", options: ["家事本來就該媽媽一個人做", "誰有空誰做，不用特別分", "分了反而大家更偷懶", "互相幫忙、分擔工作"], answer: 3, hints: ["想想全部家事都丟給一個人會怎樣", "分著做才不會太累"], explanation: "家人分工能讓每人做擅長的事，分擔家計與家務，家庭生活才會更順利。" },
    { id: "el-soc-family-3", prompt: "小華家只有爸爸、媽媽和他同住，這是哪一種家庭？", options: ["小家庭", "大家庭", "單親家庭", "隔代教養家庭"], answer: 0, hints: ["小家庭是父母與子女同住", "沒有和長輩同住"], explanation: "父母和子女同住、沒有和長輩一起住的家庭，稱為小家庭。" },
    { id: "el-soc-family-4", prompt: "下列哪一項是家人對我們的照顧？", options: ["只盯著我們寫功課", "陪我們長大、準備三餐", "什麼事都不讓我們自己做", "做錯事就罰零用錢"], answer: 1, hints: ["想想家人平常為你做的事", "照顧包含生活和陪伴"], explanation: "家人會準備三餐、接送陪伴，在生活與情感上照顧我們長大。" },
    { id: "el-soc-family-5", prompt: "關於『家庭樹』，下列哪個說法正確？", options: ["就是家裡院子種的那棵樹", "只有大家庭才需要畫", "從『我』往上可找到父母和祖父母", "只能畫爸爸那一邊的長輩"], answer: 2, hints: ["家庭樹是表示親屬關係的圖", "從自己往上推長輩"], explanation: "家庭樹是表示親屬關係的圖，不是真的樹；從『我』往上能找出父母、祖父母。" },
    { id: "el-soc-family-6", prompt: "小婷主動幫忙洗碗、倒垃圾，這最能說明什麼？", options: ["她只是想跟媽媽討獎品", "她可能想逃避寫功課", "家事本來就只能大人做", "家人分工我也有一份"], answer: 3, hints: ["分擔家事是家庭分工", "小孩也能盡一份力"], explanation: "家庭分工不分年齡，孩子主動分擔家事，也是在為家裡盡一份心力。" },
  ],
};

const EL_SOC_SCHOOL_RULES: OnionLesson = {
  id: "el-soc-school-rules",
  title: "校園生活與規則",
  subject: "社會",
  topic: "校園生活與規則",
  grade: "三上",
  stages: ["國小"],
  desc: "為什麼學校要有規則？遵守規則能讓大家安心學習、平安上課。",
  takeaways: [
    "校園規則是為了保護大家的安全與學習權利",
    "排隊、禮讓、保持安靜都是常見的校園規則",
    "遵守規則能讓教室和校園更和諧有序",
    "不同場所各有配合目的的規則；規則也可與大家討論、隨需要調整",
  ],
  frames: [
    { id: 1, step: "步驟 1：想想校園為何要有規則", caption: "你有沒有想過，為什麼學校要訂這麼多規則？如果完全沒有規則，校園會變怎樣？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：說出常見校園規則", caption: "我們一起來看，校園常見的規則有排隊、禮讓、上課保持安靜這些。", action: "point", prop: { kind: "text", text: "規則：排隊、禮讓、安靜", sub: "讓大家有秩序", tone: "ok" }, duration: 3600 },
    { id: 3, step: "步驟 3：不同場所不同規則", caption: "你有沒有發現，圖書館要安靜、營養午餐要排隊、操場可以跑，不同地方規則不一樣。", action: "point", prop: { kind: "text", text: "圖書館安靜、用餐排隊", sub: "配合場所目的訂規則", tone: "ok" }, duration: 3600, ask: { prompt: "在圖書館裡，應該遵守什麼規則？", options: ["保持安靜、輕聲交談", "圖書館很大，可以盡情奔跑", "看書肚子餓了可以吃零食", "書架很多，大聲講話也沒人聽到"], answer: 0, hint: "想想別人正在看書，你大聲會怎樣？" } },
    { id: 4, step: "步驟 4：規則保護安全", caption: "記得哦，規則其實在保護我們，像不推擠、走廊靠右走，才不會受傷。", action: "think", prop: { kind: "text", text: "規則保護：安全＋學習", sub: "不推擠才不會受傷", tone: "ok" }, duration: 3600, ask: { prompt: "為什麼下課要排隊不推擠？", options: ["排隊看起來比較整齊好看", "避免推擠受傷、保護安全", "排隊的人可以先挑喜歡的菜", "這是營養午餐規定，別無理由"], answer: 1, hint: "推擠容易撞到人或跌倒。" } },
    { id: 5, step: "步驟 5：規則守護學習", caption: "你想想看，上課保持安靜，大家才能專心聽課，不會被別人打斷。", action: "point", prop: { kind: "text", text: "安靜等於專心聽課", sub: "不打擾別人學習", tone: "ok" }, duration: 3600 },
    { id: 6, step: "步驟 6：一起遵守規則", caption: "有沒有發現，每個人都守規則時，教室和校園自然就變得有秩序。", action: "jump", prop: { kind: "flow", steps: ["我守規則", "同學也守規則", "校園更和諧"], active: 1 }, duration: 3600, ask: { prompt: "下列哪一項是遵守校園規則的表現？", options: ["排隊禮讓不推擠", "老師轉身就和同學聊天", "垃圾先塞進抽屜回家再丟", "下課鈴一響就衝出教室"], answer: 0, hint: "守規則是尊重自己也尊重別人。" } },
    { id: 7, step: "步驟 7：班規大家一起訂", caption: "我們一起來看，班規可以由大家一起討論出來，才是全班共同的約定。", action: "walk", prop: { kind: "flow", steps: ["提出想法", "大家一起討論", "形成班規"], active: 2 }, duration: 3600 },
    { id: 8, step: "步驟 8：規則可隨需要調整", caption: "記得哦，規則不是不能改；發現哪裡不方便，可以和大家再討論、修訂。", action: "walk", prop: { kind: "text", text: "規則可隨需要修訂", sub: "更好守、更合理", tone: "ok" }, duration: 3400 },
    { id: 9, step: "步驟 9：整理規則重點", caption: "我們一起記住：規則保安全、安靜好學習、守規則更和諧。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-school-rules-1", prompt: "下列哪一項是常見的校園規則？", options: ["下課在走廊追逐奔跑", "老師講課時插嘴聊天", "領餐時排隊禮讓", "垃圾隨手丟在走廊"], answer: 2, hints: ["規則讓大家有秩序", "排隊是常見的好習慣"], explanation: "排隊、禮讓能維持校園秩序，保護大家安全，是常見的校園規則。" },
    { id: "el-soc-school-rules-2", prompt: "上課為什麼要保持安靜？", options: ["老師耳朵不好怕吵", "安靜的教室比較涼爽", "學校規定上課不能說話", "讓大家能專心聽課不被打擾"], answer: 3, hints: ["安靜能幫助學習", "不打擾別人也是尊重"], explanation: "上課安靜能讓自己和同學專心吸收，也是尊重彼此的學習權利。" },
    { id: "el-soc-school-rules-3", prompt: "小華在走廊不小心推人，這違反了哪個觀念？", options: ["走廊不推擠、保護安全", "下課可以盡情奔跑", "說話要輕聲細語", "用完物品要歸位"], answer: 0, hints: ["推擠容易讓人受傷", "規則要保護安全"], explanation: "走廊人多狹窄，推擠容易讓人跌倒受傷，這正是安全規則要避免的。" },
    { id: "el-soc-school-rules-4", prompt: "班級規則最好是怎麼訂出來的？", options: ["由老師一個人決定就好", "師生一起討論形成", "導學年的規定直接拿來用", "不用訂，大家自動會守"], answer: 1, hints: ["大家一起參與會更願意遵守", "共同討論出的規則更合理"], explanation: "班規由師生共同討論形成，會更貼近需求，大家也更願意遵守。" },
    { id: "el-soc-school-rules-5", prompt: "關於校園規則，下列哪個說法正確？", options: ["規則是用來處罰不守規矩的人", "規則一多，校園反而更混亂", "規則讓大家安心學習與活動", "規則只在下課吃飯時才有用"], answer: 2, hints: ["規則保護安全與學習", "規則讓校園更有秩序"], explanation: "校園規則的目的是保護安全與學習權利，讓全校師生都能安心活動。" },
    { id: "el-soc-school-rules-6", prompt: "下雨天走廊容易濕滑，學校可增加什麼貼心規則？", options: ["下雨天更要衝刺才不會淋濕", "濕地板剛好，可以玩水", "不用規定，自己小心就好", "走廊禁止奔跑、放慢腳步快走"], answer: 3, hints: ["避免滑倒受傷", "和安全有關"], explanation: "地面潮濕容易滑倒，增設『走廊不奔跑』是依環境調整的安全規則。" },
  ],
};

const EL_SOC_COMMUNITY: OnionLesson = {
  id: "el-soc-community",
  title: "社區與家鄉",
  subject: "社會",
  topic: "社區與家鄉",
  grade: "三下",
  stages: ["國小"],
  desc: "家裡附近有哪些公共設施？公園、圖書館、市場怎麼幫助生活？",
  takeaways: [
    "社區是住家附近的生活圈，有各種公共設施",
    "公園、圖書館、市場等設施方便我們的日常生活",
    "愛護公共設施、與鄰居和睦相處，社區更美好",
    "公共設施由政府與大眾共同維護、開放使用；參與社區事務能讓家鄉更美好",
  ],
  frames: [
    { id: 1, step: "步驟 1：看看家附近生活圈", caption: "你有沒有發現，住家附近有公園、圖書館、市場？這些地方到底怎麼幫助我們生活？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：找出社區公共設施", caption: "我們一起來看，社區常見的公共設施有公園、圖書館、市場和車站。", action: "point", prop: { kind: "text", text: "公共設施：公園、圖書館、市場", sub: "大家一起使用的空間", tone: "ok" }, duration: 3600 },
    { id: 3, step: "步驟 3：公共設施大家共用", caption: "記得哦，公園、圖書館由公家維護、平時開放，住附近的人都能使用。", action: "point", prop: { kind: "text", text: "公共設施：大家共用", sub: "由公家維護開放", tone: "ok" }, duration: 3600, ask: { prompt: "為什麼說社區公園是『公共』設施？", options: ["社區的人都可以使用", "只有繳管理費的住戶能進", "只有住一樓的住戶方便去", "它是裡面攤商私人的產業"], answer: 0, hint: "想想誰能進去玩？需要付錢給私人嗎？" } },
    { id: 4, step: "步驟 4：認識公園的好處", caption: "你想想看，公園可以運動、散步，也常碰到鄰居，彼此就變得更熟識。", action: "think", prop: { kind: "text", text: "公園：運動＋交朋友", sub: "讓身心更健康", tone: "ok" }, duration: 3600, ask: { prompt: "下列哪一項是社區的公共設施？", options: ["自己家的客廳", "社區鄰里公園", "家裡的書桌", "自己的臥室"], answer: 1, hint: "公共設施是大家都能使用的。" } },
    { id: 5, step: "步驟 5：比較各設施使用人次", caption: "你看數字就知道：每週公園 120 人、圖書館 80 人、市場 100 人使用。", action: "point", prop: { kind: "bars", items: [{ label: "公園", value: 120 }, { label: "圖書館", value: 80 }, { label: "市場", value: 100 }], unit: "人", active: 0 }, duration: 3800 },
    { id: 6, step: "步驟 6：市場與日常生活", caption: "你有沒有發現，市場能買到新鮮蔬菜和日用品，叫我們的日常採買更方便。", action: "jump", prop: { kind: "flow", steps: ["買菜", "買日用品", "和攤販聊天"], active: 0 }, duration: 3600, ask: { prompt: "圖書館對社區有什麼幫助？", options: ["借書閱讀、安靜學習", "可以借錢給有需要的人", "販售新鮮水果與青菜", "規畫成停車場使用"], answer: 0, hint: "圖書館是閱讀和學習的地方。" } },
    { id: 7, step: "步驟 7：一起愛護公共設施", caption: "記得哦，公共設施是大家共用的，我們要愛惜、不破壞，和鄰居和睦相處。", action: "walk", prop: { kind: "flow", steps: ["不破壞", "用完歸位", "和大家分享"], active: 1 }, duration: 3600 },
    { id: 8, step: "步驟 8：一起參與社區事務", caption: "我們一起來，除了愛惜設施，也可以參加社區打掃、鄰里活動，讓家附近更有溫度。", action: "walk", prop: { kind: "flow", steps: ["參與打掃", "鄰里活動", "社區更有愛"], active: 1 }, duration: 3400 },
    { id: 9, step: "步驟 9：整理社區重點", caption: "我們一起記住：社區有設施、大家共用、愛惜更美好。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-community-1", prompt: "下列哪一項屬於社區的公共設施？", options: ["自己家的客廳", "房間裡的私人書桌", "社區鄰里公園", "家裡的主臥室"], answer: 2, hints: ["公共設施是大家都能用的", "公園是開放的空間"], explanation: "社區公園是開放給大眾使用的公共設施；客廳、臥室是私人空間。" },
    { id: "el-soc-community-2", prompt: "市場對我們的生活有什麼用處？", options: ["假日去看熱鬧的地方", "可以借閱圖書的地方", "適合跑步運動的場所", "買到新鮮蔬菜和日用品"], answer: 3, hints: ["市場可以買食材和用品", "方便每天的食衣需求"], explanation: "市場集合許多攤商，方便我們買到新鮮食材與日常用品。" },
    { id: "el-soc-community-3", prompt: "根據使用人次，哪一個設施每週最多人使用？", options: ["公園", "市場", "圖書館", "三個一樣多"], answer: 0, hints: ["看哪個數字最大", "公園是 120 人"], explanation: "公園每週 120 人，多於市場 100 人與圖書館 80 人，所以公園最多人使用。" },
    { id: "el-soc-community-4", prompt: "為什麼我們要愛惜公共設施？", options: ["壞了自然有人會修理", "它是大家一起用的共享資源", "塗鴉之後比較有藝術感", "管理員會負責全部賠償"], answer: 1, hints: ["公共設施是共享的", "愛惜才能長久使用"], explanation: "公共設施由大眾共用，愛惜它才能讓所有人都能長久方便使用。" },
    { id: "el-soc-community-5", prompt: "關於社區，下列哪個說法正確？", options: ["社區就是自己家裡那棟樓", "公共設施只有大人才能使用", "社區是住家附近的生活圈", "鄰居不相識，不用打招呼"], answer: 2, hints: ["社區包含家與附近設施", "是生活的範圍"], explanation: "社區是住家附近的生活範圍，包含住家與大家共用的公共設施。" },
    { id: "el-soc-community-6", prompt: "社區公園的遊戲器材壞了，最適當的做法是？", options: ["反正不是我弄壞的，放著不管", "看哪個零件還能用，拆回家", "再搖晃看看是不是真的壞了", "告知管理單位或里長協助修繕"], answer: 3, hints: ["公共設施大家共用", "回報才能儘快修復"], explanation: "公共設施損壞應回報管理單位或里長，才能儘快修復、保障大家安全。" },
  ],
};

const EL_SOC_MAP_DIRECTION: OnionLesson = {
  id: "el-soc-map-direction",
  title: "地圖與方位",
  subject: "社會",
  topic: "地圖與方位",
  grade: "四上",
  stages: ["國小"],
  desc: "地圖怎麼看？上北下南、比例尺算距離、圖例認符號，洋蔥教你讀圖。",
  takeaways: [
    "地圖方位口訣：上北、下南、左西、右東",
    "比例尺告訴我們圖上距離對應真實距離",
    "圖例說明地圖上各種符號代表什麼",
    "把地圖上方對準北方最容易對照實際；無指北標時預設上方即北方",
  ],
  frames: [
    { id: 1, step: "步驟 1：打開一張地圖", caption: "你有沒有想過，手拿一張地圖，要怎麼知道哪裡是北、兩地距離有多遠？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：記住方位口訣", caption: "我們一起來記口訣：看地圖先認方向，上北、下南、左西、右東。", action: "point", prop: { kind: "text", text: "上北、下南、左西、右東", sub: "看地圖先找方向", tone: "ok" }, duration: 3600 },
    { id: 3, step: "步驟 3：對照實際方向", caption: "你試試看，把地圖上方對準北方，圖上的方向就和現場對得起來，找地點更快。", action: "point", prop: { kind: "text", text: "地圖對準北方再看", sub: "圖上方向＝實際方向", tone: "ok" }, duration: 3600, ask: { prompt: "看地圖時，把地圖哪一邊對著北方最容易對照？", options: ["把地圖上方對準北方", "把地圖下方對準北方", "把地圖左邊對準北方", "地圖上下顛倒才看得懂"], answer: 0, hint: "地圖預設上北，把上方對北就對了。" } },
    { id: 4, step: "步驟 4：用比例尺算距離", caption: "記得哦，比例尺說圖上 1 公分代表真實 100 公尺，那 3 公分就是 300 公尺。", action: "think", prop: { kind: "flow", steps: ["圖上 1 公分", "代表真實 100 公尺", "兩地 3 公分為 300 公尺"], active: 2 }, duration: 3800, ask: { prompt: "地圖『上北下南』，右邊是哪個方向？", options: ["西", "東", "南", "北"], answer: 1, hint: "上北下南、左西右東，右邊是東。" } },
    { id: 5, step: "步驟 5：比例尺換算練習", caption: "我們一起算一次：圖上量到 2 公分，乘上 100 公尺，真實距離就是 200 公尺。", action: "point", prop: { kind: "flow", steps: ["量得 2 公分", "乘 100 公尺", "等於 200 公尺"], active: 2 }, duration: 3800 },
    { id: 6, step: "步驟 6：看懂圖例符號", caption: "你有沒有發現，圖例會告訴你符號意思：三角形是山、屋子是學校、波浪是河。", action: "jump", prop: { kind: "text", text: "圖例：▲山　⌂學校　≈河", sub: "符號代表真實地物", tone: "ok" }, duration: 3600, ask: { prompt: "圖上量得 4 公分，比例尺 1 公分為 50 公尺，真實多遠？", options: ["200 公尺", "把 4 加 50 算成 54 公尺", "把 4 公分直接當成 4 公尺", "誤用 1 公分等於 500 公尺"], answer: 0, hint: "4 公分乘以 50 公尺。" } },
    { id: 7, step: "步驟 7：三個工具一起用", caption: "我們一起來，看好方位、量比例尺、查圖例，三個一起用就能讀懂地圖。", action: "walk", prop: { kind: "flow", steps: ["看方位", "量比例尺", "查圖例"], active: 0 }, duration: 3600 },
    { id: 8, step: "步驟 8：沒有指北標就看上", caption: "記得哦，地圖沒畫指北標時，約定上方就是北方，照上北下南看就好。", action: "walk", prop: { kind: "text", text: "無指北標→預設上北", sub: "約定俗成的習慣", tone: "ok" }, duration: 3400 },
    { id: 9, step: "步驟 9：整理讀圖重點", caption: "我們一起記住：上北下南、比例算距、圖例認符號。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-map-direction-1", prompt: "看地圖時，『上北下南』的下方是哪一個方向？", options: ["北", "東", "南", "西"], answer: 2, hints: ["上方是北", "下方就是南"], explanation: "地圖慣例上方為北、下方為南，所以下方指的是南方。" },
    { id: "el-soc-map-direction-2", prompt: "地圖上的圖例有什麼作用？", options: ["讓地圖看起來比較漂亮", "用來計算實際距離多遠", "在地圖上指出北方在哪", "說明各符號代表什麼地物"], answer: 3, hints: ["符號需要說明才看得懂", "圖例是地圖的字典"], explanation: "圖例像地圖的字典，解釋三角形、屋子等符號分別代表什麼真實地物。" },
    { id: "el-soc-map-direction-3", prompt: "比例尺 1 公分代表 100 公尺，圖上 5 公分等於真實多少？", options: ["500 公尺", "把 5 公分當成 5 公尺", "只算一個 100 公尺", "把 5 和 100 加成 105 公尺"], answer: 0, hints: ["5 公分乘以 100 公尺", "把圖上長度放大"], explanation: "5 公分 × 100 公尺/公分 等於 500 公尺，這是換算出來的真實距離。" },
    { id: "el-soc-map-direction-4", prompt: "小文想在地圖上找學校，他應該先怎麼做？", options: ["用眼睛在地圖上慢慢猜", "先查圖例看學校的符號", "把地圖對著太陽照照看", "去問比例尺是多少"], answer: 1, hints: ["圖例告訴你符號意義", "先認符號再找位置"], explanation: "先從圖例查出學校用什麼符號，才能在地圖上快速找到它的位置。" },
    { id: "el-soc-map-direction-5", prompt: "關於地圖，下列哪個說法正確？", options: ["比例尺只是畫好看，和距離無關", "圖例是地圖上的裝飾圖案", "方位、比例尺、圖例都要會看", "地圖不用分方向，隨便看"], answer: 2, hints: ["三種工具一起用才讀得懂", "方位比例圖例都重要"], explanation: "讀懂地圖要會看方位、用比例尺算距離、查圖例認符號，三者缺一不可。" },
    { id: "el-soc-map-direction-6", prompt: "地圖上方沒有指北標，學校在公園的左邊，學校在公園的哪一邊？", options: ["東邊", "南邊", "北邊", "西邊"], answer: 3, hints: ["沒指北標→上北下南", "左邊是西"], explanation: "無指北標時預設上北下南、左西右東；公園左邊就是西邊，所以學校在公園西邊。" },
  ],
};

const EL_SOC_TAIWAN_EARLY: OnionLesson = {
  id: "el-soc-taiwan-early",
  title: "臺灣早期的開發",
  subject: "社會",
  topic: "臺灣早期的開發",
  grade: "四上",
  stages: ["國小"],
  desc: "臺灣很早就有誰來開發？原住民、荷西、明鄭到清領，洋蔥說給你聽。",
  takeaways: [
    "最早住在臺灣的是原住民各族，有自己的文化",
    "荷蘭、西班牙曾短暫統治部分地區（荷西時期）",
    "明鄭和清領時期，更多漢人來臺開墾定居",
    "原住民依山靠海發展生計；漢人移民帶來農耕技術並與原住民互動融合",
  ],
  frames: [
    { id: 1, step: "步驟 1：找找最早的居民", caption: "你有沒有想過，在荷蘭人、鄭成功來之前，臺灣這塊土地上住著誰？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：認識原住民各族", caption: "我們一起來認識，原住民各族很早就住在臺灣，有自己的語言、祭典和生活。", action: "point", prop: { kind: "text", text: "最早居民：原住民各族", sub: "有自己語言與文化", tone: "ok" }, duration: 3600 },
    { id: 3, step: "步驟 3：原住民與自然共生", caption: "你有沒有發現，住在山裡的族務農狩獵、靠海的族打漁，生活方式跟環境有關。", action: "point", prop: { kind: "text", text: "靠山務農、靠海打漁", sub: "各族因地制宜", tone: "ok" }, duration: 3600, ask: { prompt: "原住民各族的生活方式主要和什麼有關？", options: ["他們居住的環境（山或海）", "跟著外國傳教士學來的", "各族都一樣，沒有什麼差別", "因為喜歡搬家到處遷徙"], answer: 0, hint: "靠山、靠海就發展不同生計。" } },
    { id: 4, step: "步驟 4：荷西時期來臨", caption: "後來荷蘭人占南部、西班牙人占北部，歷史上把這段叫荷西時期。", action: "think", prop: { kind: "flow", steps: ["原住民定居", "荷蘭占南部", "西班牙占北部", "後荷蘭統一"], active: 1 }, duration: 3600, ask: { prompt: "臺灣最早的原住民，和後來的統治者有何不同？", options: ["原住民是漢人移民帶來的", "原住民本來就長期住在這裡", "原住民和荷蘭人同樣來自歐洲", "原住民是鄭成功來後才出現"], answer: 1, hint: "原住民比荷西、明鄭都早。" } },
    { id: 5, step: "步驟 5：明鄭時期開墾", caption: "我們一起來看，明鄭時期鄭成功來臺、趕走荷蘭，帶更多漢人開墾農地。", action: "point", prop: { kind: "flow", steps: ["鄭成功來臺", "趕走荷蘭", "漢人拓墾農地"], active: 1 }, duration: 3600 },
    { id: 6, step: "步驟 6：清領時期發展", caption: "你有沒有發現，清領時期更多漢人渡海來臺，沿海陸續出現街庄和城鎮。", action: "jump", prop: { kind: "flow", steps: ["清廷統治", "更多漢人移民", "城鎮慢慢出現"], active: 2 }, duration: 3600, ask: { prompt: "荷西、明鄭、清領，誰的時間最晚？", options: ["清領時期", "荷蘭與西班牙時期", "鄭成功的明鄭時期", "原住民定居時期"], answer: 0, hint: "順序是原住民到荷西、明鄭，最後清領。" } },
    { id: 7, step: "步驟 7：排列開發先後順序", caption: "我們一起整理順序：原住民最早，接著荷西、明鄭，最後是清領時期。", action: "walk", prop: { kind: "flow", steps: ["原住民", "荷西", "明鄭", "清領"], active: 3 }, duration: 3600 },
    { id: 8, step: "步驟 8：移民帶來新改變", caption: "記得哦，漢人移民帶來水田耕種技術，也和原住民往來交流，文化慢慢融合。", action: "walk", prop: { kind: "flow", steps: ["漢人農耕技術", "與原住民互動", "文化交流融合"], active: 2 }, duration: 3400 },
    { id: 9, step: "步驟 9：整理開發順序", caption: "我們一起記住：原住最先、荷西短暫、明鄭清領陸續開發。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-taiwan-early-1", prompt: "臺灣最早住在這裡的居民是誰？", options: ["東來的荷蘭人", "鄭成功帶來的軍隊", "原住民各族", "清代派來的官員"], answer: 2, hints: ["比荷西明鄭都早", "原本就生活在臺灣"], explanation: "原住民各族長期居住在臺灣，比荷蘭、明鄭、清領都早，是這塊土地最早的居民。" },
    { id: "el-soc-taiwan-early-2", prompt: "「荷西時期」是指哪兩個勢力？", options: ["荷蘭與英國", "西班牙與葡萄牙", "荷蘭與日本", "荷蘭與西班牙"], answer: 3, hints: ["名字裡有荷和西班", "荷蘭占南、西班牙占北"], explanation: "荷西時期指荷蘭與西班牙曾分別統治臺灣南部與北部的短暫時期。" },
    { id: "el-soc-taiwan-early-3", prompt: "明鄭時期對臺灣的開發有什麼影響？", options: ["帶來更多漢人開墾農地", "對臺灣開發幾乎沒有影響", "把原住民全部趕回山裡", "在臺灣興建了高速鐵路"], answer: 0, hints: ["鄭成功驅荷後拓墾", "漢人農業發展起來"], explanation: "鄭成功驅荷後，大量漢人移民來臺拓墾，農業逐漸發展起來。" },
    { id: "el-soc-taiwan-early-4", prompt: "清領時期臺灣出現了什麼變化？", options: ["移民變少、人口外流", "更多漢人移民、城鎮出現", "臺灣從此無人居住", "又淪為另一國殖民地"], answer: 1, hints: ["移民增加才會形成街庄", "城鎮慢慢發展"], explanation: "清領時期更多漢人渡海來臺，沿海街庄逐漸擴大，慢慢形成城鎮。" },
    { id: "el-soc-taiwan-early-5", prompt: "依開發先後排列，正確順序是？", options: ["清領→明鄭→荷西→原住民", "荷西→原住民→清領→明鄭", "原住民→荷西→明鄭→清領", "明鄭→清領→原住民→荷西"], answer: 2, hints: ["最早是原住民", "最晚是清領"], explanation: "正確順序：原住民最早，接著荷西、明鄭，最後才是清領時期。" },
    { id: "el-soc-taiwan-early-6", prompt: "明鄭、清領時期大量漢人來臺，他們主要帶來了什麼？", options: ["電腦與網際網路", "高鐵與捷運系統", "他們只帶來自己的行李", "水田農耕技術與漢人文化"], answer: 3, hints: ["移民多半是務農", "帶來耕作技術"], explanation: "漢人移民多從事農墾，帶來水田耕作技術與漢人文化，與原住民互動融合。" },
  ],
};

const EL_SOC_FESTIVALS: OnionLesson = {
  id: "el-soc-festivals",
  title: "臺灣的節慶習俗",
  subject: "社會",
  topic: "臺灣的節慶習俗",
  grade: "三下",
  stages: ["國小"],
  desc: "臺灣有哪些節慶？春節、端午、中秋和原住民祭典，各有什麼習俗？",
  takeaways: [
    "春節：過年團圓、發紅包、吃年菜",
    "端午：划龍舟、吃粽子；中秋：賞月、吃月餅",
    "原住民各族也有自己的祭典，展現文化特色",
    "節慶習俗背後常有除舊佈新、感恩團圓的心意，代代相傳成為文化資產",
  ],
  frames: [
    { id: 1, step: "步驟 1：找找一年中的節慶", caption: "你有沒有想過，為什麼一年到了某個時候，家裡就會特別熱鬧、特別忙碌？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：認識歡喜春節", caption: "我們一起來看，春節是農曆新年，全家圍爐吃年菜，長輩發紅包給小孩。", action: "point", prop: { kind: "text", text: "春節：團圓、紅包、年菜", sub: "農曆新年全家聚", tone: "ok" }, duration: 3600 },
    { id: 3, step: "步驟 3：過年習俗有意義", caption: "你有沒有發現，過年前大掃除、貼春聯、圍爐，都是為了除舊佈新、祈求平安。", action: "point", prop: { kind: "text", text: "掃除、貼春聯、圍爐", sub: "除舊佈新、祈求平安", tone: "ok" }, duration: 3600, ask: { prompt: "過年貼春聯、圍爐吃年夜飯，主要是為了什麼？", options: ["除舊佈新、祈求新歲平安團圓", "因為學校規定要寫寒假作業", "只是因為年夜飯特別好吃", "長輩規定不做會被處罰"], answer: 0, hint: "習俗背後有祈福與團圓的心意。" } },
    { id: 4, step: "步驟 4：熱鬧的端午", caption: "我們一起來認識端午：划龍舟、吃粽子，是為了紀念詩人屈原。", action: "think", prop: { kind: "text", text: "端午：龍舟、粽子", sub: "紀念屈原的節日", tone: "ok" }, duration: 3600, ask: { prompt: "春節時，長輩常會做什麼？", options: ["帶全家去划龍舟比賽", "發紅包給晚輩壓歲", "晚上賞月吃柚子", "穿傳統服飾辦祭典"], answer: 1, hint: "過年長輩會包紅包。" } },
    { id: 5, step: "步驟 5：溫馨的中秋節", caption: "你想想看，中秋節晚上賞月、吃月餅和柚子，也是一家人團聚的日子。", action: "point", prop: { kind: "text", text: "中秋：賞月、月餅", sub: "秋天團圓的節日", tone: "ok" }, duration: 3600 },
    { id: 6, step: "步驟 6：認識原住民祭典", caption: "記得哦，原住民各族有豐年祭等祭典，穿傳統服飾、唱歌跳舞感謝豐收。", action: "jump", prop: { kind: "text", text: "原住民祭典：豐年祭等", sub: "展現各族文化", tone: "ok" }, duration: 3600, ask: { prompt: "端午節常見的活動是什麼？", options: ["划龍舟、吃粽子", "晚上賞月吃柚子", "長輩發紅包給小孩", "穿傳統服飾辦祭典"], answer: 0, hint: "端午和龍舟、粽子有關。" } },
    { id: 7, step: "步驟 7：節慶隨四季循環", caption: "我們一起來看，這些節慶隨著四季輪流出現，就像一個循環的習俗圈。", action: "walk", prop: { kind: "cycle", nodes: ["春節", "端午", "中秋", "原住民祭典"], active: 0 }, duration: 3600 },
    { id: 8, step: "步驟 8：節慶背後的心意", caption: "你想想看，不論漢人節慶或原住民祭典，都在感恩自然、團聚親友，代代相傳。", action: "walk", prop: { kind: "text", text: "感恩、團圓、傳承", sub: "節慶是文化的結晶", tone: "ok" }, duration: 3400 },
    { id: 9, step: "步驟 9：整理節慶重點", caption: "我們一起記住：春團圓、端午舟、中秋月、祭典展文化。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-festivals-1", prompt: "春節時全家通常會做什麼？", options: ["划龍舟比賽", "賞月吃柚子", "圍爐吃年菜、長輩發紅包", "穿傳統服飾豐年祭"], answer: 2, hints: ["春節是農曆新年", "長輩會發紅包"], explanation: "春節是農曆新年，全家圍爐吃年菜，長輩會發紅包給晚輩。" },
    { id: "el-soc-festivals-2", prompt: "端午節的傳統活動不包括下列哪一項？", options: ["划龍舟競賽", "吃粽子", "紀念詩人屈原", "晚上賞月吃月餅"], answer: 3, hints: ["賞月是中秋的活動", "端午和龍舟粽子有關"], explanation: "賞月是中秋節的活動；端午節的傳統是划龍舟、吃粽子、紀念屈原。" },
    { id: "el-soc-festivals-3", prompt: "中秋節常會做什麼？", options: ["賞月、吃月餅和柚子", "長輩發紅包給晚輩", "河邊划龍舟比賽", "穿傳統服飾辦祭典"], answer: 0, hints: ["中秋在秋天", "和月亮有關"], explanation: "中秋節在秋天，有賞月、吃月餅與柚子的習俗，象徵團圓。" },
    { id: "el-soc-festivals-4", prompt: "原住民各族的祭典，展現了什麼？", options: ["外國傳來的節慶文化", "各族自己的文化特色", "全臺灣統一的同一種慶祝", "和漢人春節一模一樣"], answer: 1, hints: ["各族有不同祭典", "豐年祭是代表"], explanation: "原住民各族有豐年祭等不同祭典，穿傳統服飾歌舞，展現各族獨特文化。" },
    { id: "el-soc-festivals-5", prompt: "下列哪個說法正確？", options: ["臺灣一年只有春節一個節慶", "原住民祭典只是形式，不重要", "節慶隨四季輪流，各有不同習俗", "中秋節和划龍舟有關"], answer: 2, hints: ["節慶在不同季節", "各有不同習俗"], explanation: "臺灣節慶隨四季輪流出現，春節、端午、中秋與原住民祭典各具特色。" },
    { id: "el-soc-festivals-6", prompt: "中秋節為什麼常和「團圓」聯想在一起？", options: ["中秋節大家都要上班", "傳說月亮上會掉下月餅", "古時候就是隨便說說的", "月色圓滿、家人望月寄思團聚"], answer: 3, hints: ["月亮圓代表圓滿", "在外遊子賞月思親"], explanation: "中秋月色圓滿，家人團聚賞月、遊子望月思親，因此中秋象徵團圓。" },
  ],
};

const EL_SOC_GOVERNMENT: OnionLesson = {
  id: "el-soc-government",
  title: "政府的角色與選舉",
  subject: "社會",
  topic: "政府的角色與選舉",
  grade: "六上",
  stages: ["國小"],
  desc: "政府在做什麼？修橋鋪路、辦學校、保護我們，人民也能投票選代表。",
  takeaways: [
    "政府提供公共服務：教育、交通、治安、醫療等",
    "政府的錢來自稅收，用來照顧全體社會",
    "人民依法投票，選出替我們做事的代言人",
    "公立學校、自來水、道路橋樑都是公共建設；稅收取之於民、用之於民",
  ],
  frames: [
    { id: 1, step: "步驟 1：找找身邊的政府", caption: "你有沒有想過，你讀的學校、走的馬路、喝的自來水，背後是誰興建維護的？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：政府提供哪些服務", caption: "我們一起來看，政府會辦學校、修橋鋪路、維持治安、提供公共醫療。", action: "point", prop: { kind: "flow", steps: ["辦學校", "修橋鋪路", "維持治安", "公共醫療"], active: 0 }, duration: 3600 },
    { id: 3, step: "步驟 3：你身邊的政府建設", caption: "你想想看，你讀的公立學校、喝的自來水、走的柏油路，都是政府興建維護的。", action: "point", prop: { kind: "flow", steps: ["公立學校", "自來水系統", "馬路橋梁"], active: 0 }, duration: 3600, ask: { prompt: "下列哪一項是政府興辦的公共建設？", options: ["公立學校與大眾馬路", "家裡的電視遙控器", "同學帶來的玩具", "自己上學用的書包"], answer: 0, hint: "公家興建、大家共用的才是。" } },
    { id: 4, step: "步驟 4：政府的錢從哪來", caption: "記得哦，政府辦這些事的錢，來自大家繳的稅，再用來照顧社會的需要。", action: "think", prop: { kind: "flow", steps: ["大家繳稅", "政府收稅", "用在公共服務"], active: 2 }, duration: 3600, ask: { prompt: "政府辦學校、修路，錢主要來自哪裡？", options: ["向外國政府借來的錢", "人民繳納的稅收", "由央行印鈔票支應", "這些建設根本不用花錢"], answer: 1, hint: "稅收是政府的主要財源。" } },
    { id: 5, step: "步驟 5：政府保護我們", caption: "你有沒有發現，政府也會救災、照顧弱勢族群，保護大家的安全與福利。", action: "point", prop: { kind: "text", text: "政府保護：安全加福利", sub: "守護每個人", tone: "ok" }, duration: 3600 },
    { id: 6, step: "步驟 6：人民投票選代表", caption: "我們一起來看，年滿法定年齡的公民可以投票，選出替我們發聲、做事的代表。", action: "jump", prop: { kind: "flow", steps: ["登記成選民", "了解候選人", "出門投票", "選出代表"], active: 2 }, duration: 3600, ask: { prompt: "人民投票最主要的目的？", options: ["選出替自己發聲的代表", "投票可以決定明天的天氣", "選出誰當自己的同班同學", "投爽的，沒有特別目的"], answer: 0, hint: "投票是選出為我們做事的人。" } },
    { id: 7, step: "步驟 7：權利與義務並重", caption: "你想想看，我們享有公共服務，也要納稅、參與投票，這是權利也是義務。", action: "walk", prop: { kind: "flow", steps: ["享有公共服務", "履行納稅義務", "參與投票"], active: 1 }, duration: 3600 },
    { id: 8, step: "步驟 8：取之於民用之於民", caption: "記得哦，稅收來自大家，又用在學校、道路、治安上，正是取之於民、用之於民。", action: "walk", prop: { kind: "text", text: "稅收→公共建設→回歸大家", sub: "取之於民、用之於民", tone: "ok" }, duration: 3400 },
    { id: 9, step: "步驟 9：整理政府重點", caption: "我們一起記住：政府服務、稅收支應、人民投票選代表。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-government-1", prompt: "下列哪一項是政府的公共服務？", options: ["在家自己煮晚餐", "和同學聊電話", "修橋鋪路、辦公立學校", "放假在家看電視"], answer: 2, hints: ["政府做大家共用的事", "交通建設是政府職責"], explanation: "修橋鋪路、辦學校、維持治安等服務由政府提供，全民共享。" },
    { id: "el-soc-government-2", prompt: "政府的經費主要來自哪裡？", options: ["向其他國家借貸而來", "由央行自己印鈔票", "公共建設其實都免費", "人民繳納的稅收"], answer: 3, hints: ["稅收是主要財源", "大家共同分擔"], explanation: "政府經費主要來自人民繳納的稅，再用於教育、交通、治安等公共服務。" },
    { id: "el-soc-government-3", prompt: "人民參與投票，最主要可以做到什麼？", options: ["選出替自己發聲的代表", "投票能決定明天的天氣", "選出明天營養午餐菜色", "投一票就能讓學校放假"], answer: 0, hints: ["投票選出代表", "代表為我們做事"], explanation: "投票是公民參與公共事務的方式，選出替大家發聲、做事的代表。" },
    { id: "el-soc-government-4", prompt: "關於政府的角色，下列何者正確？", options: ["政府的工作就是開罰單", "提供服務也保護人民安全", "治安是警察的事，和政府無關", "稅收是大人的事，和小孩無關"], answer: 1, hints: ["政府照顧全體", "安全福利都包含"], explanation: "政府提供教育、交通、醫療等服務，也維持治安、保護人民安全與福利。" },
    { id: "el-soc-government-5", prompt: "享有政府服務的同時，我們也應該？", options: ["享受服務就好，不用做什麼", "只要求政府付出，自己不回饋", "依法納稅並參與投票", "政府規定都可以不遵守"], answer: 2, hints: ["權利義務是一體的", "繳稅投票是公民責任"], explanation: "權利與義務一體兩面，享受公共服務的同時，也應納稅、參與投票。" },
    { id: "el-soc-government-6", prompt: "人民繳的稅，下列哪一項最可能被運用？", options: ["直接放進官員的私人帳戶", "拿去辦公室團購零食", "收進國庫後就閒著不用", "興建學校、道路等公共建設"], answer: 3, hints: ["稅收用在公共服務", "取之於民用之於民"], explanation: "稅收取之於民、用之於民，主要用於教育、交通、治安、醫療等公共建設。" },
  ],
};

const EL_SOC_CONSUMPTION: OnionLesson = {
  id: "el-soc-consumption",
  title: "消費與理財",
  subject: "社會",
  topic: "消費與理財",
  grade: "六下",
  stages: ["國小"],
  desc: "買東西前先想：這是需要還是想要？記帳和儲蓄讓錢用得更聰明。",
  takeaways: [
    "需要是維持生活必需的；想要是喜歡但不一定必要",
    "記帳能清楚看見錢花到哪裡，幫助控制支出",
    "把錢存起來（儲蓄），可以應付未來的需要",
    "消費前先分辨需要與想要；廣告易誘發衝動消費，買前要停一下",
  ],
  frames: [
    { id: 1, step: "步驟 1：想想自己買過的東西", caption: "你有沒有過，看到喜歡的東西就想買，回家後才後悔？先來分清楚需要和想要。", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：分辨需要與想要", caption: "我們一起來分：需要是生活必需品，像食物衣服；想要是喜歡但不一定需要。", action: "point", prop: { kind: "text", text: "需要：食物、衣服", sub: "想要：玩具、最新手機", tone: "ok" }, duration: 3600 },
    { id: 3, step: "步驟 3：同樣東西分清楚", caption: "你有沒有發現，口渴喝水是需要；看到廣告想買昂貴飲料，就比較像想要。", action: "point", prop: { kind: "text", text: "喝水＝需要；昂貴飲料＝想要", sub: "看是否生活必需", tone: "ok" }, duration: 3600, ask: { prompt: "看到電視廣告就想立刻買下最新玩具，這比較像？", options: ["想要，因為喜歡但非必要", "需要，沒有它不能生活", "不用理會，跟自己無關", "既是需要也是想要"], answer: 0, hint: "喜歡但不一定必要，就是想要。" } },
    { id: 4, step: "步驟 4：記帳看花費", caption: "我們一起來看，記帳就是把收入和每筆花費寫下，月底就知道錢花到哪。", action: "think", prop: { kind: "flow", steps: ["寫下收入", "記每筆支出", "月底看總結"], active: 2 }, duration: 3600, ask: { prompt: "下面哪一個比較像『需要』？", options: ["最新款的電玩玩具", "每天要吃的三餐", "限量發售的球鞋", "最新型的昂貴手機"], answer: 1, hint: "需要是維持生活必需的。" } },
    { id: 5, step: "步驟 5：比較一週花費", caption: "你看數字：一週花費需要 300 元、想要 200 元，需要的花費比較多。", action: "point", prop: { kind: "bars", items: [{ label: "需要", value: 300 }, { label: "想要", value: 200 }], unit: "元", active: 0 }, duration: 3800 },
    { id: 6, step: "步驟 6：養成儲蓄習慣", caption: "記得哦，把一部分錢存起來叫儲蓄，能應付將來較大的需要。", action: "jump", prop: { kind: "text", text: "儲蓄：把錢存起來", sub: "留給未來的需要", tone: "ok" }, duration: 3600, ask: { prompt: "記帳最主要的好處是什麼？", options: ["清楚看見錢花到哪裡", "寫下數字錢就會變多", "記了帳就不能再花錢", "有記帳就可以不用工作"], answer: 0, hint: "記帳幫你看清支出。" } },
    { id: 7, step: "步驟 7：聰明消費三步", caption: "我們一起記三步：先分需要或想要、再記帳看支出、最後把錢存起來。", action: "walk", prop: { kind: "flow", steps: ["想需要或想要", "先記帳", "再儲蓄"], active: 1 }, duration: 3600 },
    { id: 8, step: "步驟 8：小心衝動消費", caption: "你想想看，廣告常讓我們心動、一時衝動亂買；買前停一下問自己：我真的需要嗎？", action: "walk", prop: { kind: "text", text: "廣告心動→停一下", sub: "想清楚再買不遲", tone: "warn" }, duration: 3400 },
    { id: 9, step: "步驟 9：整理理財重點", caption: "我們一起記住：需要優先、記帳看清、儲蓄備未來。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-consumption-1", prompt: "下列哪一項屬於『需要』？", options: ["最新款遊戲主機", "昂貴的名牌球鞋", "每天要吃的三餐", "限量版公仔模型"], answer: 2, hints: ["需要是生活必需", "吃飯維持生命"], explanation: "三餐是維持生命必需的『需要』；遊戲機、球鞋、模型多屬『想要』。" },
    { id: "el-soc-consumption-2", prompt: "『想要』和『需要』最大的差別是？", options: ["兩者價格其實一樣", "想要的東西通常比較便宜", "需要和想要根本是同一回事", "需要是生活必要、想要是喜歡但非必要"], answer: 3, hints: ["需要不能少", "想要可以省下"], explanation: "需要是少了就不能正常生活的項目，想要是喜歡但沒有也不會影響生活。" },
    { id: "el-soc-consumption-3", prompt: "小美一週需要花 300 元、想要花 200 元，哪個多？", options: ["需要 300 元比較多", "想要 200 元比較多", "兩者都是 250 元一樣多", "小美這週都沒花錢"], answer: 0, hints: ["比較 300 和 200", "需要是 300 元"], explanation: "需要 300 元多於想要 200 元，比較兩個數字可知需要的花費較多。" },
    { id: "el-soc-consumption-4", prompt: "為什麼要養成記帳的習慣？", options: ["寫下數字，錢就會自己變多", "清楚每筆支出、幫助控制花費", "有記帳本，店家就送東西", "開始記帳就不用再賺錢"], answer: 1, hints: ["記帳看見錢去哪", "才能控制預算"], explanation: "記帳讓我們看清錢花到哪，進而控制預算、避免不必要的消費。" },
    { id: "el-soc-consumption-5", prompt: "關於儲蓄，下列哪個說法正確？", options: ["儲蓄就是把手邊的錢全部花光", "儲蓄是大人的事，小孩不用做", "把一部分錢存起來，備未來需要", "只有很有錢的人才需要儲蓄"], answer: 2, hints: ["儲蓄是累積備用", "未來有大需要時可用"], explanation: "儲蓄是把一部分錢累積起來，未來遇到較大需要時才不至於周轉不靈。" },
    { id: "el-soc-consumption-6", prompt: "小華看到同學有新限量卡片就跟著買，回家才後悔。這提醒我們？", options: ["同學有的東西自己也要有", "卡片蒐集愈多愈好", "跟風買東西不用記帳", "跟風衝動消費前要先分辨需要"], answer: 3, hints: ["一時跟著別人買", "沒想清楚就花錢"], explanation: "因同儕壓力或廣告一時跟風購物，容易買到非真正需要的東西；買前停一下分辨需要與想要。" },
  ],
};

const EL_SOC_GLOBAL: OnionLesson = {
  id: "el-soc-global",
  title: "世界大不同與國際交流",
  subject: "社會",
  topic: "世界大不同與國際交流",
  grade: "六下",
  stages: ["國小"],
  desc: "世界各國文化不同：語言、食物、服飾都不一樣，互相尊重就能好好交流。",
  takeaways: [
    "各國文化不同：語言、食物、服飾、節慶各有特色",
    "面對差異要尊重與包容，不嘲笑、不歧視",
    "國際組織和交流讓各國合作、互相幫助",
    "各國飲食、服飾差異常和氣候與歷史有關；了解由來更能尊重包容",
  ],
  frames: [
    { id: 1, step: "步驟 1：打開世界地圖", caption: "你有沒有想過，為什麼外國朋友吃飯、打招呼的方式和我們不一樣？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：看見文化差異", caption: "我們一起來看，不同國家有不同語言、食物和服飾，這就是文化差異。", action: "point", prop: { kind: "text", text: "差異：語言、食物、服飾", sub: "各國都有自己的特色", tone: "ok" }, duration: 3600 },
    { id: 3, step: "步驟 3：見面禮節各不同", caption: "你有沒有發現，有的國家見面握手、有的雙手合十、有的貼臉頰問好，方式大不同。", action: "point", prop: { kind: "text", text: "握手／合十／貼臉頰", sub: "問候方式各有文化", tone: "ok" }, duration: 3600, ask: { prompt: "遇到外國朋友用我們不習慣的問候方式，最好怎麼做？", options: ["入境隨俗、尊重對方的方式", "笑他的動作很奇怪", "要求他改用我們的方式", "假裝沒看到躲開他"], answer: 0, hint: "各國禮節不同，尊重最重要。" } },
    { id: 4, step: "步驟 4：尊重與包容", caption: "記得哦，遇到不同文化，我們要尊重包容，不嘲笑、也不歧視。", action: "think", prop: { kind: "text", text: "尊重：不嘲笑、不歧視", sub: "包容讓世界更友善", tone: "ok" }, duration: 3600, ask: { prompt: "看到別國不同的習俗，最好怎麼做？", options: ["覺得奇怪就嘲笑兩句", "尊重包容、不歧視", "要求對方改成和我們一樣", "覺得和自己無關，完全不理"], answer: 1, hint: "尊重差異能友好相處。" } },
    { id: 5, step: "步驟 5：各國節慶也不同", caption: "你想想看，各國節慶也不同，像嘉年華、潑水節，都是當地寶貴的文化。", action: "point", prop: { kind: "text", text: "各國節慶不同", sub: "都是珍貴的文化", tone: "ok" }, duration: 3600 },
    { id: 6, step: "步驟 6：國際組織合作", caption: "我們一起來看，各國透過國際組織合作，一起訂規則、解決跨國的問題。", action: "jump", prop: { kind: "flow", steps: ["各國加入組織", "一起訂規則", "合作解決問題"], active: 2 }, duration: 3600, ask: { prompt: "國際組織的主要功能是什麼？", options: ["讓各國合作解決跨國問題", "每年固定舉辦運動比賽", "強制全世界說同一種話", "它成立以來沒有任何作用"], answer: 0, hint: "各國一起合作才辦得到。" } },
    { id: 7, step: "步驟 7：交流帶來友誼", caption: "你有沒有發現，國際交流讓我們認識不同文化、互相學習，也交到外國朋友。", action: "walk", prop: { kind: "flow", steps: ["認識不同文化", "互相學習", "成為朋友"], active: 1 }, duration: 3600 },
    { id: 8, step: "步驟 8：差異背後有道理", caption: "記得哦，各國吃什麼、穿什麼，常和當地氣候、歷史有關；了解原因就更能尊重。", action: "walk", prop: { kind: "text", text: "飲食穿著←氣候歷史", sub: "理解差異的由來", tone: "ok" }, duration: 3400 },
    { id: 9, step: "步驟 9：整理交流重點", caption: "我們一起記住：文化有差異、尊重能包容、交流交朋友。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-global-1", prompt: "下列何者屬於『文化差異』的例子？", options: ["各國餐桌上都吃同一道菜", "全世界的人都說同一種語言", "各國有不同的語言和服飾", "每個國家的衣服都長一樣"], answer: 2, hints: ["差異是不同的地方", "語言服飾各國不同"], explanation: "不同國家有各自的語言、食物、服飾與節慶，這些就是文化差異。" },
    { id: "el-soc-global-2", prompt: "面對和自己不同的文化，應該怎麼做？", options: ["覺得奇怪就笑對方", "要求對方改成和自己一樣", "既然不同就不要往來", "尊重包容、不嘲笑也不歧視"], answer: 3, hints: ["尊重才能友好", "包容讓世界友善"], explanation: "每種文化都有其背景，面對差異應尊重包容，才能與不同文化的人友好相處。" },
    { id: "el-soc-global-3", prompt: "為什麼國際組織對各國有幫助？", options: ["讓各國合作解決跨國問題", "主要功能是舉辦運動比賽", "強制把大家的想法變一樣", "成立以來根本沒有作用"], answer: 0, hints: ["問題常跨國界", "合作力量大"], explanation: "環境、防疫等問題常跨越國界，國際組織讓各國坐下來合作解決。" },
    { id: "el-soc-global-4", prompt: "下列哪一個是國際交流的好處？", options: ["交流之後每個國家都更閉關", "認識不同文化、結交外國朋友", "交流的目的是消滅所有差異", "交流後只能和本國人說話"], answer: 1, hints: ["交流是互相認識", "學習對方文化"], explanation: "國際交流讓我們走出自己的文化，認識別國特色，也建立友誼。" },
    { id: "el-soc-global-5", prompt: "關於文化差異，下列哪個說法正確？", options: ["文化差異代表哪國比較進步", "和自己不同的習俗都很好笑", "差異值得尊重，不必分高下", "只有自己國家的文化最好"], answer: 2, hints: ["每種文化都珍貴", "尊重不比較高下"], explanation: "文化差異沒有優劣之分，每種文化都有其價值，都應被尊重。" },
    { id: "el-soc-global-6", prompt: "日本人吃飯前習慣雙手合十說「我開動了」，我們應該怎麼看待？", options: ["這個動作很奇怪，應該嘲笑", "請他們改成我們的用餐習慣", "覺得這種做法很可笑", "那是他們的文化禮節，給予尊重"], answer: 3, hints: ["各國禮節不同", "文化差異要尊重"], explanation: "雙手合十指感謝食材與準備者，是日本飲食文化的禮節；面對不同習俗應尊重。" },
  ],
};

const EL_SOC_TRANSPORT: OnionLesson = {
  id: "el-soc-transport",
  title: "交通與通訊的演變",
  subject: "社會",
  topic: "交通與通訊的演變",
  grade: "四下",
  stages: ["國小"],
  desc: "交通和通訊怎麼進步？從走路、火車到高鐵，從書信到手機網路，洋蔥帶你看。",
  takeaways: [
    "交通工具從步行、牛車到火車、汽車、高鐵，越來越快",
    "通訊從書信、電報到電話、網路，越來越即時",
    "進步讓人與人聯繫更方便，生活圈也變大了",
    "交通通訊進步源於節省時間、擴大生活圈的需求；使用之餘應節能減碳愛護地球",
  ],
  frames: [
    { id: 1, step: "步驟 1：回到從前的生活", caption: "你有沒有想過，阿公阿嬤年輕時，要怎麼聯絡住在遠方的親人？", action: "wave", prop: { kind: "none" }, duration: 3000 },
    { id: 2, step: "步驟 2：交通的演變", caption: "我們一起來看，交通工具從步行、牛車，進步到火車、汽車，現在還有高鐵。", action: "point", prop: { kind: "flow", steps: ["步行", "牛車", "火車", "汽車高鐵"], active: 3 }, duration: 3600 },
    { id: 3, step: "步驟 3：為什麼要更快", caption: "你有沒有發現，人們想更快到更遠的地方，交通工具才從走路一路進步到高鐵、飛機。", action: "point", prop: { kind: "text", text: "需求變多→交通變快", sub: "節省移動時間", tone: "ok" }, duration: 3600, ask: { prompt: "人們不斷追求更快的交通工具，最主要是為了什麼？", options: ["節省移動時間、拓展生活圈", "買好車比較有面子", "閒著沒事做研發新東西", "為了多消耗汽油"], answer: 0, hint: "快就能省下時間、拓展生活圈。" } },
    { id: 4, step: "步驟 4：速度越來越快", caption: "記得哦，演變讓速度愈來愈快：步行最慢、火車變快、高鐵又更快。", action: "think", prop: { kind: "flow", steps: ["步行最慢", "火車變快", "高鐵最快"], active: 2 }, duration: 3600, ask: { prompt: "下列交通工具，哪個速度通常最快？", options: ["用雙腿步行", "高速鐵路高鐵", "牛拉的牛車", "腳踩的腳踏車"], answer: 1, hint: "高鐵是目前最快的大眾運輸。" } },
    { id: 5, step: "步驟 5：通訊的演變", caption: "我們一起來看，通訊從書信、電報、電話，到現在用手機和網路即時聯絡。", action: "point", prop: { kind: "flow", steps: ["書信", "電報", "電話", "網路手機"], active: 3 }, duration: 3600 },
    { id: 6, step: "步驟 6：聯絡越來越即時", caption: "你有沒有發現，書信要等好幾天，網路訊息卻秒到，聯絡愈來愈即時。", action: "jump", prop: { kind: "flow", steps: ["書信要等", "電報較快", "網路秒到"], active: 2 }, duration: 3600, ask: { prompt: "從書信進步到網路，通訊變得怎樣？", options: ["更即時、更方便聯絡", "比寄信還要慢又麻煩", "和從前完全沒有差別", "網路時代只能寫文字"], answer: 0, hint: "網路訊息立刻送達。" } },
    { id: 7, step: "步驟 7：生活圈變大了", caption: "你想想看，交通快、通訊即時，我們的生活圈變大，和遠方親友聯絡更方便。", action: "walk", prop: { kind: "flow", steps: ["移動快", "聯絡易", "生活圈擴大"], active: 2 }, duration: 3600 },
    { id: 8, step: "步驟 8：進步也要愛地球", caption: "記得哦，交通方便之餘也要節能減碳：多搭大眾運輸、少開車，愛護地球。", action: "walk", prop: { kind: "text", text: "多搭大眾運輸", sub: "節能減碳、愛地球", tone: "ok" }, duration: 3400 },
    { id: 9, step: "步驟 9：整理演變重點", caption: "我們一起記住：步行到高鐵、書信到網路、進步更方便。預備，闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "el-soc-transport-1", prompt: "下列交通工具，哪一個出現得最晚？", options: ["用雙腿步行", "牛拉的牛車", "高速鐵路高鐵", "蒸汽火車"], answer: 2, hints: ["高鐵是現代科技", "比火車更新"], explanation: "高鐵是現代科技產物，比步行、牛車、火車都晚出現。" },
    { id: "el-soc-transport-2", prompt: "通訊從書信進步到網路，最大的改變是？", options: ["訊息送達得比從前更慢", "寄一封信要等更久", "網路時代只能寫紙本信", "訊息即時送達，更方便"], answer: 3, hints: ["網路訊息立刻到", "不用再等郵差"], explanation: "網路讓訊息瞬間送達，省去書信等待好幾天的時間，更即時方便。" },
    { id: "el-soc-transport-3", prompt: "交通進步對我們有什麼影響？", options: ["移動更快、生活圈變大", "距離變遠，生活圈反而變小", "從此大家都只能待在家", "進步之後大家都不出門"], answer: 0, hints: ["速度快才能去遠處", "聯繫也變容易"], explanation: "交通工具愈快，能抵達的範圍愈遠，生活圈自然隨之擴大。" },
    { id: "el-soc-transport-4", prompt: "下列哪一項屬於『早期』的通訊方式？", options: ["用手機即時視訊", "透過郵差寄送書信", "用手機網路傳訊息", "在社群軟體留言"], answer: 1, hints: ["書信要寄送等待", "是古老的方式"], explanation: "書信郵寄要透過郵差、等待好幾天，是早期的通訊方式。" },
    { id: "el-soc-transport-5", prompt: "關於交通與通訊演變，下列哪個說法正確？", options: ["交通和通訊都愈來愈慢", "高鐵的速度比步行還慢", "進步讓人與人聯繫更方便", "寄書信比網路訊息更即時"], answer: 2, hints: ["進步是為了便利", "速度和即時都提升"], explanation: "交通與通訊不斷進步，使人們移動更快、聯絡更即時方便。" },
    { id: "el-soc-transport-6", prompt: "高鐵和大眾運輸又快又方便，但我們仍應呼籲什麼？", options: ["鼓勵大家一人開一台車出門", "把公路改建成賽車跑道", "廢氣多一點也無所謂", "多騎車搭大眾運輸、節能減碳"], answer: 3, hints: ["節能減碳", "大眾運輸較省能"], explanation: "交通工具便利但仍耗能排碳，多搭大眾運輸或騎車走路，能節能減碳愛護地球。" },
  ],
};

export default [
  EL_SOC_FAMILY,
  EL_SOC_SCHOOL_RULES,
  EL_SOC_COMMUNITY,
  EL_SOC_MAP_DIRECTION,
  EL_SOC_TAIWAN_EARLY,
  EL_SOC_FESTIVALS,
  EL_SOC_GOVERNMENT,
  EL_SOC_CONSUMPTION,
  EL_SOC_GLOBAL,
  EL_SOC_TRANSPORT,
];
