/**
 * 國中英語補充課程（洋蔥學院 200 堂擴充計畫：二、國中新增 45 堂／英語 8 堂）。
 *
 * 內容依 docs/onion-200-plan.md 的課表撰寫；每一堂都是 9 幀步驟分鏡
 * （字幕用中文講解、英文例句內嵌）＋ 3 次中途提問 ＋ 7 題闖關。
 */
import type { OnionLesson } from "@/game/onionAcademyLessons";

const JH_ENG_PAST: OnionLesson = {
  id: "jh-eng-past",
  title: "過去簡單式：昨天發生的事",
  subject: "英語",
  topic: "過去簡單式",
  grade: "七下",
  stages: ["國中"],
  desc: "把時間調到昨天，動詞要跟著變身。規則動詞加 -ed、不規則動詞要背，否定和問句交給 did。",
  takeaways: ["過去式動詞：規則加 -ed，不規則要記（go→went）", "否定用 did not ＋ 原形動詞", "問句用 Did 開頭，後面的動詞用原形", "加 -ed 有拼字規則：e 結尾加 -d、子音+y 改 y 為 i 再加 -ed、短母音單節雙寫末字母"],
  frames: [
    { step: "步驟 1：把時間調到昨天", id: 1, caption: "今天做的事用現在式，昨天做的事就要換成過去式；你看，play 到昨天就變成 played 了。", action: "wave", prop: { kind: "text", text: "today: I play → yesterday: I played", sub: "時間一變，動詞就要變", tone: "ok" }, duration: 3200 },
    { step: "步驟 2：規則動詞加 ed", id: 2, caption: "規則動詞最單純，字尾直接加 -ed：play 變 played、watch 變 watched，讀起來也很規律。", action: "point", prop: { kind: "flow", steps: ["play", "＋ed", "played"], active: 2 }, duration: 3200 },
    { step: "步驟 3：記三個拼字小規則", id: 3, caption: "加 -ed 有三個小變化哦：e 結尾只加 d、子音加 y 要改 y 為 i、短母音單節記得雙寫末字母。", action: "point", prop: { kind: "flow", steps: ["like→liked", "study→studied", "stop→stopped"], active: 2 }, duration: 3800 },
    { step: "步驟 4：不規則動詞要背", id: 4, caption: "有些動詞不照規則走，go 變 went、eat 變 ate、see 變 saw，這些得一個一個記起來。", ask: { prompt: "「我昨天去了學校」應該怎麼說？", options: ["I went to school yesterday.", "I goed to school yesterday.", "I go to school yesterday.", "I am going to school yesterday."], answer: 0, hint: "yesterday 是過去；go 的過去式要背，不是直接加 ed。" }, action: "think", prop: { kind: "text", text: "go → went、eat → ate、see → saw", sub: "不規則動詞靠記憶，沒有規則可推", tone: "ok" }, duration: 3600 },
    { step: "步驟 5：否定交給 did not", id: 5, caption: "要說昨天沒做的事，記得用 did not 加原形動詞；did 一出現，後面動詞就回到原形。", action: "walk", prop: { kind: "balance", left: "did not", right: "＋ 原形動詞", tip: "did 後面的動詞一定回到原形" }, duration: 3400 },
    { step: "步驟 6：問句用 Did 開頭", id: 6, caption: "問句就把 Did 搬到句首：Did you play basketball yesterday? 回答用 Yes, I did. 就可以了。", ask: { prompt: "「你昨天看電視了嗎？」的正確問句是？", options: ["Do you watch TV yesterday?", "Did you watch TV yesterday?", "Did you watched TV yesterday?", "Are you watch TV yesterday?"], answer: 1, hint: "Did 開頭，後面動詞用原形 watch。" }, action: "jump", prop: { kind: "flow", steps: ["Did", "＋ 主詞", "＋ 原形動詞 ?"], active: 2 }, duration: 3600 },
    { step: "步驟 7：實戰填對過去式", id: 7, caption: "你自己試一題：時間副詞是 last night，動詞 study 要怎麼變成過去式？想想子音加 y 的規則。", ask: { prompt: "「He ___ (study) English last night.」空格應填入？", options: ["studied", "studyed", "studies", "study"], answer: 0, hint: "last night 是過去；study 是子音+y，改 y 為 i 再加 -ed。" }, action: "think", prop: { kind: "text", text: "study → studied", sub: "子音＋y：去 y 加 -ied", tone: "ok" }, duration: 3800 },
    { step: "步驟 8：提醒三個常見錯", id: 8, caption: "有沒有發現三個最常見的錯？did 後面又加 ed、問句忘記 Did、時間對了卻沒把動詞變過去。", action: "point", prop: { kind: "text", text: "✗ He did not played. → ✓ He did not play.", sub: "did 出現時，動詞一律回原形", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：口訣收束", id: 9, caption: "記起來囉：規則加 ed、不規則要背，否定問句交給 did、動詞回原形。預備，我們來闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "jh-eng-past-1", prompt: "「我昨天寫了功課。」下列哪一句正確？", options: ["I write my homework yesterday.", "I wrote my homework yesterday.", "I writed my homework yesterday.", "I did wrote my homework yesterday."], answer: 1, hints: ["yesterday 表示過去", "write 是不規則動詞，不能直接加 ed"], explanation: "write 的過去式是不規則的 wrote，不能直接加 ed 變成 writed；did 後面也不能再加過去式。" },
    { id: "jh-eng-past-2", prompt: "「他昨天沒有來學校。」應該怎麼說？", options: ["He did not came to school yesterday.", "He wasn't come to school yesterday.", "He did not come to school yesterday.", "He doesn't come to school yesterday."], answer: 2, hints: ["did not 後面要用原形動詞", "come 的原形就是 come"], explanation: "did not 之後一律接原形動詞，所以是 did not come；be 動詞 wasn't 不能這樣配原形動詞 come。" },
    { id: "jh-eng-past-3", prompt: "「你昨天有打電話給我嗎？」的正確問句是？", options: ["Do you called me yesterday?", "Did you called me yesterday?", "Were you call me yesterday?", "Did you call me yesterday?"], answer: 3, hints: ["過去式的問句用 Did 開頭", "Did 後面的動詞用原形"], explanation: "過去式問句為 Did ＋ 主詞 ＋ 原形動詞，所以是 Did you call me yesterday?" },
    { id: "jh-eng-past-4", prompt: "下列哪一個動詞的過去式「不規則」？", options: ["eat", "play", "watch", "study"], answer: 0, hints: ["規則動詞直接加 -ed", "eat 的過去式不是 eated"], explanation: "eat 的過去式是 ate，屬於不規則動詞；play、watch、study 都是規則變化。" },
    { id: "jh-eng-past-5", prompt: "「They ___ to the zoo last Sunday.」空格應填入？", options: ["go", "went", "goes", "going"], answer: 1, hints: ["last Sunday 是過去時間", "go 的過去式是 went"], explanation: "last Sunday 表示過去，主詞 They 接 go 的過去式 went；goes 是現在式、going 缺助動詞。" },
    { id: "jh-eng-past-6", prompt: "「I ___ (stop) the car five minutes ago.」空格應填入？", options: ["stoped", "stop", "stopped", "stops"], answer: 2, hints: ["stop 是短母音單節字", "字節 cvc 要雙寫末字母再加 -ed"], explanation: "stop 字尾是「子音-母音-子音」，雙寫 p 再加 -ed 故為 stopped；stoped 忘記雙寫、stops 是現在式。" },
    { id: "jh-eng-past-7", prompt: "「He ___ (like) the movie when he was young.」空格應填入？", options: ["likeed", "liking", "likes", "liked"], answer: 3, hints: ["字尾是 e 結尾", "e 結尾只加 -d"], explanation: "like 已結尾 e，直接加 -d 即 liked，不需重複 e；likeed 是多寫了一個 e。" },
  ],
};

const JH_ENG_FUTURE: OnionLesson = {
  id: "jh-eng-future",
  title: "未來式：will 與 be going to",
  subject: "英語",
  topic: "未來式",
  grade: "八上",
  stages: ["國中"],
  desc: "兩句都講未來，但一個是「當下決定」、一個是「早就計畫好」。搞清楚差別，英文就不會用錯。",
  takeaways: ["will ＋ 原形動詞：當下決定、臨時起意", "be going to ＋ 原形動詞：事先計畫、有跡象", "否定：will not；問句：Will you…?", "口說常縮寫 I'm going to / He's going to；兩者後面都接原形動詞，不加 -s"],
  frames: [
    { step: "步驟 1：未來有兩種說法", id: 1, caption: "講未來的時候，英文有兩把鑰匙：will 和 be going to，先來看看它們各自長什麼樣。", action: "wave", prop: { kind: "flow", steps: ["will ＋ 原形", "be going to ＋ 原形"], active: 0 }, duration: 3200 },
    { step: "步驟 2：will 是當下決定", id: 2, caption: "電話忽然響了，你脫口說 I will answer it. 這是講話當下才決定的事，所以用 will。", action: "point", prop: { kind: "text", text: "I will answer it.", sub: "當下決定、臨時起意 → will", tone: "ok" }, duration: 3400 },
    { step: "步驟 3：be going to 是早就計畫", id: 3, caption: "如果你早就排好週末要去爬山，就會說 I am going to go hiking this weekend，用 be going to。", ask: { prompt: "「我打算下週去臺南。」哪一句最合適？", options: ["I am going to go to Tainan next week.", "I will go to Tainan next week.", "I am go to Tainan next week.", "I went to Tainan next week."], answer: 0, hint: "已經計畫好的事，用 be going to。" }, action: "think", prop: { kind: "text", text: "I am going to go to Tainan.", sub: "事先計畫好的安排 → be going to", tone: "ok" }, duration: 3600 },
    { step: "步驟 4：有跡象也用 be going to", id: 4, caption: "看到烏雲密布，你直覺 It is going to rain. 有明顯跡象的時候，也是用 be going to。", action: "walk", prop: { kind: "text", text: "It is going to rain.", sub: "有跡象（烏雲）→ be going to", tone: "ok" }, duration: 3400 },
    { step: "步驟 5：be going to 的縮寫", id: 5, caption: "口說常常縮寫：I am going to 變 I'm going to、He is going to 變 He's going to，後面還是接原形。", action: "point", prop: { kind: "text", text: "I am going to → I'm going to", sub: "縮寫後動詞仍用原形", tone: "ok" }, duration: 3400 },
    { step: "步驟 6：否定與問句", id: 6, caption: "否定和問句別亂變形：will not 是 won't，問句用 Will you come? 後面動詞照樣用原形。", ask: { prompt: "「你不會遲到吧？」的問句應該怎麼說？", options: ["Will you late?", "Will you be late?", "Are you late?", "Will you being late?"], answer: 1, hint: "未來問句用 Will 開頭，後面要接原形動詞。" }, action: "jump", prop: { kind: "balance", left: "Will ＋ 主詞 ＋ 原形 ?", right: "won't ＋ 原形", tip: "問句與否定都保持原形動詞" }, duration: 3600 },
    { step: "步驟 7：判斷哪個用哪個", id: 7, caption: "你來判斷看看：這件事是剛才才決定，還是早就計畫好、有跡象？想清楚再選。", ask: { prompt: "「桌上蛋糕看起來很好吃，我吃一個。」（當下才決定）用哪個？", options: ["I'll have one.", "I'm going to have one.", "I have one.", "I had one."], answer: 0, hint: "當下看到蛋糕才決定，用 will。" }, action: "think", prop: { kind: "balance", left: "臨時起意 → will", right: "計畫/跡象 → be going to", tip: "看決定的時機" }, duration: 3800 },
    { step: "步驟 8：提醒常見的錯", id: 8, caption: "最常見的錯就是 will 後面亂加東西：記住 will 後面永遠是原形，不加 to 也不加 s。", action: "point", prop: { kind: "text", text: "✗ She will goes. → ✓ She will go.", sub: "will 後面的動詞不加 s、不變形", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：口訣收束", id: 9, caption: "口訣：臨時決定用 will，計畫好或看跡象用 be going to；兩個後面都接原形動詞。預備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "jh-eng-future-1", prompt: "「我打算明年學吉他。」哪一句最合適？", options: ["I will learn guitar next year.", "I am going to learn guitar next year.", "I learn guitar next year.", "I learned guitar next year."], answer: 1, hints: ["這是已經想好的計畫", "計畫好的事用 be going to"], explanation: "已經計畫好的未來安排用 be going to，所以是 I am going to learn guitar next year." },
    { id: "jh-eng-future-2", prompt: "「電話響了，我去接。」（當下決定）應該說？", options: ["I am going to answer it.", "I answer it.", "I will answer it.", "I answered it."], answer: 2, hints: ["這是講話當下才決定的", "臨時起意用 will"], explanation: "當下決定的未來動作使用 will，所以是 I will answer it." },
    { id: "jh-eng-future-3", prompt: "下列哪一句是正確的？", options: ["She will goes to Japan.", "She will to go to Japan.", "She wills go to Japan.", "She will go to Japan."], answer: 3, hints: ["will 是助動詞，後面接原形動詞", "主詞是第三人稱也不加 s"], explanation: "will 之後一律接原形動詞，不隨主詞變化，所以是 She will go to Japan." },
    { id: "jh-eng-future-4", prompt: "看到天空烏雲密布，最自然的說法是？", options: ["It is going to rain.", "It will rain tomorrow.", "It rains.", "It rained."], answer: 0, hints: ["有明顯跡象時用 be going to", "烏雲就是那個跡象"], explanation: "有明顯跡象（烏雲）時用 be going to，所以是 It is going to rain." },
    { id: "jh-eng-future-5", prompt: "「They ___ arrive at six.」（已經安排好的班機）空格應填入？", options: ["will", "are going to", "is going to", "going to"], answer: 1, hints: ["主詞 They 要接 are", "已經安排好的行程用 be going to"], explanation: "主詞 They 接 are going to，表示已經安排好的未來行程；is 跟單數、going to 缺 be 動詞。" },
    { id: "jh-eng-future-6", prompt: "口說中「I am going to read」常縮寫成？", options: ["I going to read", "I'm go to read", "I'm going to read", "I'm going read"], answer: 2, hints: ["I am 縮成 I'm", "be going to 中的 to 保留"], explanation: "I am going to 縮寫為 I'm going to，後面仍接原形動詞 read。" },
    { id: "jh-eng-future-7", prompt: "下列哪一句「有文法錯誤」？", options: ["I will call you later.", "It is going to snow.", "They are going to move.", "She wills help us."], answer: 3, hints: ["will 不能加 s", "助動詞不隨主詞變化"], explanation: "will 是助動詞，第三人稱也不加 -s；應改為 She will help us." },
  ],
};

const JH_ENG_COMPARATIVE: OnionLesson = {
  id: "jh-eng-comparative",
  title: "比較級與最高級：誰比誰高？",
  subject: "英語",
  topic: "比較級與最高級",
  grade: "八上",
  stages: ["國中"],
  desc: "兩個人比用比較級＋than，三個以上選第一用最高級＋the。短音節加 -er/-est，長音節用 more/most。",
  takeaways: ["比較級：-er 或 more，後面常接 than", "最高級：-est 或 most，前面要加 the", "不規則變化：good→better→best", "拼字：y 結尾改 y 為 i 加 -er、短母音單節雙寫末字母、e 結尾只加 -r"],
  frames: [
    { step: "步驟 1：先看要比幾個", id: 1, caption: "英文的「比」分兩種哦：兩個人在比要說誰比較怎樣，三個人以上要選出第一名。", action: "wave", prop: { kind: "flow", steps: ["比較級：兩個人比", "最高級：三個以上選第一"], active: 0 }, duration: 3200 },
    { step: "步驟 2：用長條比身高", id: 2, caption: "你看教具：Amy 150 公分、Ben 165 公分，Ben 比較高，英文就說 Ben is taller than Amy。", action: "point", prop: { kind: "bars", items: [{ label: "Amy 150", value: 150 }, { label: "Ben 165", value: 165 }], unit: "公分", active: 1 }, duration: 3400 },
    { step: "步驟 3：記三個拼字規則", id: 3, caption: "加 -er 也有小變化：y 結尾改 y 為 i、短母音單節雙寫末字母、e 結尾只加 -r。", action: "point", prop: { kind: "flow", steps: ["happy→happier", "big→bigger", "large→larger"], active: 1 }, duration: 3800 },
    { step: "步驟 4：比較級的句型", id: 4, caption: "句型很簡單：A ＋ is ＋ 比較級 ＋ than ＋ B。你試試看，「這本比那本便宜」該怎麼說？", ask: { prompt: "「這本書比那本書便宜。」應該怎麼說？", options: ["This book is cheaper than that one.", "This book is cheap than that one.", "This book is cheapest than that one.", "This book is more cheap than that one."], answer: 0, hint: "cheap 是短音節形容詞，直接加 -er 就好。" }, action: "think", prop: { kind: "balance", left: "Ben", right: "taller than Amy", tip: "比較級後面用 than 帶出對手" }, duration: 3600 },
    { step: "步驟 5：長音節用 more", id: 5, caption: "遇到音節長的形容詞就不要硬加 -er，改用 more：more beautiful、more expensive 就對了。", action: "walk", prop: { kind: "text", text: "more beautiful / more expensive", sub: "長音節形容詞用 more ＋ 原級", tone: "ok" }, duration: 3400 },
    { step: "步驟 6：最高級要加 the", id: 6, caption: "三個人以上選第一，最高級前面要記得加 the：Ben is the fastest in his class.", ask: { prompt: "「他是班上跑最快的。」應該怎麼說？", options: ["He is fastest than his class.", "He is the fastest in his class.", "He is faster in his class.", "He is more fast in his class."], answer: 1, hint: "最高級前面要加 the，範圍用 in his class 表示。" }, action: "jump", prop: { kind: "bars", items: [{ label: "Ben 14 秒", value: 14 }, { label: "Ken 15 秒", value: 15 }, { label: "Tom 16 秒", value: 16 }], unit: "秒", active: 0 }, duration: 3600 },
    { step: "步驟 7：判斷比較級或最高級", id: 7, caption: "你來判斷：句中有 than、又只有兩個對象，就用比較級；三個以上才用最高級。", ask: { prompt: "「This box is ___ than that one.」（只有兩個箱子）空格應填入？", options: ["heavier", "heaviest", "heavy", "more heavy"], answer: 0, hint: "句中有 than、只有兩者，用比較級。" }, action: "think", prop: { kind: "balance", left: "兩者 ＋ than → 比較級", right: "三者以上 → the ＋ 最高級", tip: "看對比對象數目" }, duration: 3800 },
    { step: "步驟 8：不規則變化要背", id: 8, caption: "有幾個常見字完全不照規則：good 變 better 再變 best，這些要特別背起來。", action: "point", prop: { kind: "text", text: "good → better → best", sub: "bad → worse → worst；many → more → most", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：口訣收束", id: 9, caption: "口訣：兩人比用 -er 加 than，三人以上用 the 加 -est，長音節改 more、most。預備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "jh-eng-comparative-1", prompt: "「This bag is ___ than that one.」空格應填入？", options: ["heavy", "heavier", "heaviest", "more heavy"], answer: 1, hints: ["句子裡有 than，要用比較級", "heavy 去 y 加 -ier"], explanation: "有 than 表示兩者比較，heavy 的比較級是 heavier（去 y 加 -ier）；more heavy 是錯誤用法。" },
    { id: "jh-eng-comparative-2", prompt: "「它是店裡最貴的鞋。」應該怎麼說？", options: ["It is more expensive shoes in the store.", "It is expensive than the store.", "It is the most expensive shoes in the store.", "It is the expensivest shoes in the store."], answer: 2, hints: ["三個以上選第一，用最高級", "expensive 是長音節，用 most"], explanation: "最高級用 the most expensive，範圍用 in the store 表示；expensivest 是硬加 -est 的錯誤。" },
    { id: "jh-eng-comparative-3", prompt: "下列哪一組是正確的不規則變化？", options: ["good → gooder → goodest", "good → more good → most good", "good → best → better", "good → better → best"], answer: 3, hints: ["good 的比較級不是加 -er", "這是必須背下來的變化"], explanation: "good 的比較級是 better、最高級是 best，屬於不規則變化，gooder、more good 都錯。" },
    { id: "jh-eng-comparative-4", prompt: "「Ken runs faster ___ Tom.」空格應填入？", options: ["than", "then", "that", "as"], answer: 0, hints: ["比較級後面要帶出對手", "注意 than 與 then 拼字不同"], explanation: "比較級後面接 than（不是 then，then 是「然後」），用來帶出比較對象。" },
    { id: "jh-eng-comparative-5", prompt: "三個同學比身高，要用哪一句？", options: ["Amy is taller than Ben.", "Amy is the tallest of the three.", "Amy is tall than Ben.", "Amy is more tall of the three."], answer: 1, hints: ["三個以上選第一用最高級", "最高級前面加 the，範圍用 of the three"], explanation: "三者以上比較用最高級：Amy is the tallest of the three；tall than 缺 -er。" },
    { id: "jh-eng-comparative-6", prompt: "「happy」的比較級是？", options: ["happyer", "more happy", "happier", "happiest"], answer: 2, hints: ["y 結尾改 y 為 i", "再加 -er"], explanation: "happy 是子音+y，去 y 加 -ier 故 happier；happyer 是忘了改 y。" },
    { id: "jh-eng-comparative-7", prompt: "「big」的最高級是？", options: ["bigest", "more big", "most big", "biggest"], answer: 3, hints: ["短母音單節字", "雙寫 g 再加 -est"], explanation: "big 字尾 cvc，雙寫 g 再加 -est 故 biggest；bigest 忘記雙寫 g。" },
  ],
};

const JH_ENG_GERUND: OnionLesson = {
  id: "jh-eng-gerund",
  title: "動名詞與不定詞：to V 還是 V-ing？",
  subject: "英語",
  topic: "動名詞與不定詞",
  grade: "八下",
  stages: ["國中"],
  desc: "有些動詞後面只能接 to V，有些只能接 V-ing，還有些兩個都可以。用一張分類表把它記牢。",
  takeaways: ["不定詞 to ＋ 原形動詞：want to go", "動名詞 V-ing 當名詞用：enjoy swimming", "有些動詞兩種都可以：like to swim / like swimming", "口訣：want/hope/plan/decide 接 to V；enjoy/finish/practice/mind 接 V-ing"],
  frames: [
    { step: "步驟 1：動詞後面接什麼", id: 1, caption: "英文句子常出現兩個動詞排在一起，第二個到底要用 to V 還是 V-ing？這堂來搞清楚。", action: "wave", prop: { kind: "flow", steps: ["want to go", "enjoy swimming"], active: 0 }, duration: 3200 },
    { step: "步驟 2：to V 指還沒做", id: 2, caption: "want、hope、plan、decide 後面接 to V，像 I want to go home，通常指還沒做的動作。", action: "point", prop: { kind: "text", text: "want / hope / plan / decide ＋ to V", sub: "指向還沒做的動作", tone: "ok" }, duration: 3400 },
    { step: "步驟 3：V-ing 當名詞用", id: 3, caption: "enjoy、finish、practice 後面要接 V-ing：I enjoy swimming，這裡 swimming 就當名詞用。", ask: { prompt: "「我喜歡游泳。」哪一句正確？", options: ["I enjoy swimming.", "I enjoy to swim.", "I enjoy swim.", "I enjoy to swimming."], answer: 0, hint: "enjoy 後面只能接 V-ing。" }, action: "think", prop: { kind: "text", text: "enjoy / finish / practice ＋ V-ing", sub: "V-ing 在這裡當名詞用", tone: "ok" }, duration: 3600 },
    { step: "步驟 4：背只接 V-ing 的動詞", id: 4, caption: "把只接 V-ing 的動詞記成一群：enjoy、finish、practice、mind、suggest、avoid，後面都加 V-ing。", action: "point", prop: { kind: "flow", steps: ["enjoy / finish", "practice / mind", "suggest / avoid"], active: 2 }, duration: 3400 },
    { step: "步驟 5：片語動詞看尾字", id: 5, caption: "片語裡的 to 不一定是不定詞哦：look forward to seeing you，這個 to 是介系詞，後面接 V-ing。", action: "walk", prop: { kind: "text", text: "look forward to seeing you", sub: "片語裡的 to 是介系詞，後面接 V-ing", tone: "ok" }, duration: 3600 },
    { step: "步驟 6：兩個都可以的動詞", id: 6, caption: "like、love、start 這幾個兩種都行：I like to swim 跟 I like swimming，意思差不多。", ask: { prompt: "下列哪一個動詞後面「只能」接 to V？", options: ["enjoy", "decide", "finish", "practice"], answer: 1, hint: "想想哪一個是「決定、計畫」那一類的動詞。" }, action: "jump", prop: { kind: "text", text: "like to swim ＝ like swimming", sub: "意思相同，兩種寫法都對" }, duration: 3600 },
    { step: "步驟 7：動手判斷 to 還是 V-ing", id: 7, caption: "實戰：看到第二個動詞，先認前面那個動詞屬於哪一組，再決定寫 to 還是 V-ing。", ask: { prompt: "「Would you mind ___ the window?」空格應填入？", options: ["closing", "to close", "close", "closed"], answer: 0, hint: "mind 屬於只接 V-ing 的那一組。" }, action: "think", prop: { kind: "balance", left: "want/decide → to V", right: "enjoy/mind → V-ing", tip: "分類先背熟" }, duration: 3800 },
    { step: "步驟 8：提醒最常見的錯", id: 8, caption: "最常見的錯就是分類記反：enjoy 後面加了 to、want 後面用了 V-ing，可別靠感覺。", action: "point", prop: { kind: "text", text: "✗ I enjoy to swim. → ✓ I enjoy swimming.", sub: "分類要背，不能憑語感", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：口訣收束", id: 9, caption: "口訣：want、hope、decide 接 to V；enjoy、finish、practice 接 V-ing；like 兩種都行。預備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "jh-eng-gerund-1", prompt: "「我決定學日文。」應該怎麼說？", options: ["I decide learning Japanese.", "I decide to learn Japanese.", "I decide learn Japanese.", "I decide to learning Japanese."], answer: 1, hints: ["decide 後面接 to V", "to 後面要用原形動詞"], explanation: "decide 後面接不定詞 to V，所以是 decide to learn；decide 不接動名詞。" },
    { id: "jh-eng-gerund-2", prompt: "「他練習彈鋼琴。」應該怎麼說？", options: ["He practices to play the piano.", "He practices play the piano.", "He practices playing the piano.", "He practices to playing the piano."], answer: 2, hints: ["practice 後面接 V-ing", "就像 enjoy 那一類"], explanation: "practice 後面接動名詞 V-ing，所以是 practices playing." },
    { id: "jh-eng-gerund-3", prompt: "「I look forward to ___ you.」空格應填入？", options: ["see", "saw", "to see", "seeing"], answer: 3, hints: ["look forward to 是片語，to 是介系詞", "介系詞後面接 V-ing"], explanation: "look forward to 的 to 是介系詞，後面接動名詞 seeing，不是不定詞。" },
    { id: "jh-eng-gerund-4", prompt: "下列哪一句是錯誤的？", options: ["I finished to do my homework.", "I want to go home.", "I enjoy reading.", "I hope to see you soon."], answer: 0, hints: ["finish 後面只能接 V-ing", "找那個動詞用錯形式的句子"], explanation: "finish 後面要接 V-ing，應改為 I finished doing my homework." },
    { id: "jh-eng-gerund-5", prompt: "「I like ___ basketball.」哪一種說法都可以？", options: ["只能填 to play", "to play 或 playing 都可以", "只能填 playing", "只能填 play"], answer: 1, hints: ["like 屬於兩種都行的動詞", "意思差不多"], explanation: "like 後面接 to play 或 playing 都可以，意思相近，不必二選一。" },
    { id: "jh-eng-gerund-6", prompt: "「I suggest ___ a rest.」空格應填入？", options: ["to take", "take", "taking", "took"], answer: 2, hints: ["suggest 屬於只接 V-ing 的動詞", "建議用動名詞"], explanation: "suggest 後面接動名詞 taking，故 I suggest taking a rest." },
    { id: "jh-eng-gerund-7", prompt: "「He avoids ___ late.」空格應填入？", options: ["to be", "be", "been", "being"], answer: 3, hints: ["avoid 是只接 V-ing 的動詞", "避免做某事用 avoid V-ing"], explanation: "avoid 後面接動名詞，故 being late；avoid 不接不定詞 to be。" },
  ],
};

const JH_ENG_RELATIVE: OnionLesson = {
  id: "jh-eng-relative",
  title: "關係子句：用 who 和 which 加補充",
  subject: "英語",
  topic: "關係子句",
  grade: "九上",
  stages: ["國中"],
  desc: "把兩句合成一句：人用 who、事物用 which／that。學會之後，句子可以又短又清楚。",
  takeaways: ["先行詞是人 → who；是事物 → which／that", "關係子句緊跟在先行詞後面", "關係代名詞當主詞時，後面動詞跟著先行詞變", "先行詞表「誰的」用 whose；受格關係代名詞常可省略"],
  frames: [
    { step: "步驟 1：兩句變一句", id: 1, caption: "「我有一個朋友。他會彈吉他。」這兩句太鬆散了，其實可以合成一句，靠的就是關係子句。", action: "wave", prop: { kind: "flow", steps: ["I have a friend.", "He can play the guitar.", "I have a friend who can play the guitar."], active: 2 }, duration: 3600 },
    { step: "步驟 2：人用 who", id: 2, caption: "先行詞是人就用 who：the boy who is running、the girl who sings well，很好記。", action: "point", prop: { kind: "text", text: "人 → who", sub: "the boy who is running", tone: "ok" }, duration: 3200 },
    { step: "步驟 3：事物用 which", id: 3, caption: "先行詞是事物就用 which 或 that：the book which is on the desk 兩種寫法都對。", ask: { prompt: "「那隻在睡覺的貓」應該怎麼說？", options: ["the cat which is sleeping", "the cat who is sleeping", "the cat which sleeping", "the cat is sleeping which"], answer: 0, hint: "貓是動物、不是人，用 which。" }, action: "think", prop: { kind: "text", text: "事物 → which / that", sub: "the book which is on the desk", tone: "ok" }, duration: 3600 },
    { step: "步驟 4：whose 表誰的", id: 4, caption: "要說「誰的東西」就用 whose：the boy whose bag is red，指的就是那個紅包包的男孩。", action: "point", prop: { kind: "text", text: "whose ＝ 誰的", sub: "the boy whose bag is red", tone: "ok" }, duration: 3400 },
    { step: "步驟 5：子句緊跟先行詞", id: 5, caption: "關係子句一定要緊跟在它修飾的名詞後面，位置一放錯，意思整個就跑掉了。", action: "walk", prop: { kind: "flow", steps: ["先行詞", "＋ 關係代名詞", "＋ 子句"], active: 1 }, duration: 3400 },
    { step: "步驟 6：動詞跟著先行詞", id: 6, caption: "關係代名詞當主詞時，後面動詞要跟先行詞一致：a boy 用 speaks，boys 才用 speak。", ask: { prompt: "「那個會說英文的男孩」應該怎麼說？", options: ["the boy who speak English", "the boy who speaks English", "the boy which speaks English", "the boy who speaking English"], answer: 1, hint: "先行詞是單數 boy，動詞要加 s。" }, action: "jump", prop: { kind: "balance", left: "the boy who speaks", right: "the boys who speak", tip: "動詞單複數跟著先行詞" }, duration: 3600 },
    { step: "步驟 7：動手合併兩句", id: 7, caption: "動手合併：先選對關係代名詞，再看先行詞單複數把動詞改對。你試試看。", ask: { prompt: "「我認識一個會彈鋼琴的女生。」正確合併是？", options: ["I know a girl who plays the piano.", "I know a girl which plays the piano.", "I know a girl who play the piano.", "I know a girl she plays the piano."], answer: 0, hint: "人用 who，單數 girl 動詞加 s。" }, action: "think", prop: { kind: "flow", steps: ["先行詞：a girl（人）", "用 who", "動詞 plays"], active: 2 }, duration: 3800 },
    { step: "步驟 8：提醒常見的錯", id: 8, caption: "常見的錯有兩種：人和物用錯代名詞，或是子句裡又重複寫一次主詞，記得別再寫一次。", action: "point", prop: { kind: "text", text: "✗ the man who he is tall → ✓ the man who is tall", sub: "關係子句裡不要再重複主詞", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：口訣收束", id: 9, caption: "口訣：人用 who、物用 which 或 that，子句緊跟先行詞，動詞跟著先行詞變。預備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "jh-eng-relative-1", prompt: "「我認識一位住在高雄的女生。」應該怎麼說？", options: ["I know a girl which lives in Kaohsiung.", "I know a girl who lives in Kaohsiung.", "I know a girl who live in Kaohsiung.", "I know a girl she lives in Kaohsiung."], answer: 1, hints: ["先行詞 a girl 是人", "單數主詞動詞要加 s"], explanation: "人是 who，且 a girl 為單數，動詞用 lives；which 用於事物、live 沒加 s。" },
    { id: "jh-eng-relative-2", prompt: "「這是我昨天買的書。」應該怎麼說？", options: ["This is the book who I bought yesterday.", "This is the book which I buy yesterday.", "This is the book which I bought yesterday.", "This is the book it I bought yesterday."], answer: 2, hints: ["先行詞 the book 是事物，用 which", "yesterday 要用過去式"], explanation: "事物用 which，過去時間用 bought，所以是 the book which I bought yesterday." },
    { id: "jh-eng-relative-3", prompt: "「The students ___ are playing basketball are my classmates.」空格應填入？", options: ["which", "whose", "it", "who"], answer: 3, hints: ["先行詞 students 是人", "複數動詞 are 已經放在子句裡"], explanation: "先行詞是人（students），關係代名詞用 who；whose 是所有格、which 用於事物。" },
    { id: "jh-eng-relative-4", prompt: "下列哪一句是錯誤的？", options: ["The girl who she sings well is my sister.", "The man who is standing there is my uncle.", "The dog which is barking is mine.", "The book that I read was interesting."], answer: 0, hints: ["關係子句裡不要再重複主詞", "找那個多寫了一次主詞的句子"], explanation: "who 已經代替 the girl 當主詞，不能再寫 she，應改為 The girl who sings well is my sister." },
    { id: "jh-eng-relative-5", prompt: "「他養了一隻會說話的鳥。」應該怎麼說？", options: ["He has a bird who can talk.", "He has a bird which can talk.", "He has a bird which can talks.", "He has a bird it can talk."], answer: 1, hints: ["鳥是動物，用 which", "can 後面接原形動詞"], explanation: "動物用 which，can 後面接原形 talk，所以是 a bird which can talk；can talks 多了 s。" },
    { id: "jh-eng-relative-6", prompt: "「那個眼鏡破了的男生」應說？", options: ["the boy who glasses are broken", "the boy which glasses are broken", "the boy whose glasses are broken", "the boy glasses whose are broken"], answer: 2, hints: ["要表「他的眼鏡」", "所有格用 whose"], explanation: "表「誰的」用 whose，後接名詞 glasses，故 the boy whose glasses are broken." },
    { id: "jh-eng-relative-7", prompt: "「I like the gift ___ you gave me.」關係代名詞可省略，因為它在子句中是？", options: ["主詞", "所有格", "be 動詞", "受詞"], answer: 3, hints: ["you gave 後面缺受詞", "關係代名詞當受詞時常可省"], explanation: "the gift 是 gave 的受詞，關係代名詞 which/that 當受詞可省略，直接寫 you gave me 即可。" },
  ],
};

const JH_ENG_CONJUNCTION: OnionLesson = {
  id: "jh-eng-conjunction",
  title: "連接詞：because、when、if",
  subject: "英語",
  topic: "連接詞與副詞子句",
  grade: "八下",
  stages: ["國中"],
  desc: "一句話不夠用的時候，就用連接詞把原因、時間、條件接上去。位置放前面或後面都行。",
  takeaways: ["because 表原因、when 表時間、if 表條件", "副詞子句可放句首或句尾；放句首要加逗號", "副詞子句裡用「現在式」表未來", "because 已含「所以」，不可再與 so 連用"],
  frames: [
    { step: "步驟 1：一句話不夠用", id: 1, caption: "想講「因為下雨，所以我帶傘」這種有因果的句子，一個句子不夠，就要用連接詞接起來。", action: "wave", prop: { kind: "flow", steps: ["It rained.", "I took an umbrella.", "Because it rained, I took an umbrella."], active: 2 }, duration: 3600 },
    { step: "步驟 2：because 講原因", id: 2, caption: "because 帶出原因：I was late because the bus broke down. 放句首也可以，記得加逗號。", action: "point", prop: { kind: "text", text: "because ＋ 原因", sub: "Because it rained, I took an umbrella.", tone: "ok" }, duration: 3400 },
    { step: "步驟 3：when 講時間", id: 3, caption: "when 帶出時間：When I got home, my mother was cooking. 兩個動作誰先誰後要說清楚。", ask: { prompt: "「我到家時，媽媽正在煮飯。」應該怎麼說？", options: ["When I got home, my mother was cooking.", "When I get home, my mother cooks.", "Because I got home, my mother was cooking.", "If I got home, my mother was cooking."], answer: 0, hint: "時間用 when，回家是過去發生的事。" }, action: "think", prop: { kind: "flow", steps: ["When I got home", "my mother was cooking"], active: 0 }, duration: 3600 },
    { step: "步驟 4：if 講條件", id: 4, caption: "if 帶出條件：If it rains tomorrow, we will stay home，條件成立，結果才會發生。", action: "walk", prop: { kind: "flow", steps: ["If it rains tomorrow", "we will stay home"], active: 0 }, duration: 3400 },
    { step: "步驟 5：三種連接詞對照", id: 5, caption: "三個連接詞這樣分：because 問為什麼、when 問什麼時候、if 問在什麼條件下。", action: "point", prop: { kind: "balance", left: "because 為什麼", right: "when 何時 / if 條件", tip: "看題目問什麼" }, duration: 3400 },
    { step: "步驟 6：未來的事用現在式", id: 6, caption: "重要規則：if 和 when 的子句講未來也要用現在式，記住是 If it rains，不是 will rain。", ask: { prompt: "「如果他明天來，我就會告訴他。」空格應填入？", options: ["If he will come tomorrow, I will tell him.", "If he comes tomorrow, I will tell him.", "If he came tomorrow, I will tell him.", "If he coming tomorrow, I will tell him."], answer: 1, hint: "if 子句講未來要用現在式。" }, action: "jump", prop: { kind: "balance", left: "If ＋ 現在式", right: "主要子句 ＋ will", tip: "if 子句不用 will" }, duration: 3600 },
    { step: "步驟 7：動手選連接詞", id: 7, caption: "你來選連接詞：看兩句之間是因果、時間還是條件，對號入座就不會錯。", ask: { prompt: "「___ you finish your homework, you can watch TV.」（條件）空格應填入？", options: ["If", "Because", "Who", "Which"], answer: 0, hint: "完成功課是「條件」，用 if。" }, action: "think", prop: { kind: "balance", left: "原因 → because", right: "條件 → if", tip: "判斷兩句關係" }, duration: 3800 },
    { step: "步驟 8：提醒常見的錯", id: 8, caption: "常見的錯有三個：because 和 so 同時用、if 子句加了 will、句首放子句忘了逗號。", action: "point", prop: { kind: "text", text: "✗ Because it rained, so I took an umbrella.", sub: "because 與 so 只留一個", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：口訣收束", id: 9, caption: "口訣：原因 because、時間 when、條件 if；子句放句首要逗號，講未來用現在式。預備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "jh-eng-conjunction-1", prompt: "「因為下雨，我帶了傘。」應該怎麼說？", options: ["Because it rained, so I took an umbrella.", "Because it rained, I took an umbrella.", "Because it rained, I take an umbrella.", "If it rained, I took an umbrella."], answer: 1, hints: ["because 和 so 不能同時出現", "過去的事要用過去式"], explanation: "because 與 so 只能留一個；帶傘是過去的事，用 took." },
    { id: "jh-eng-conjunction-2", prompt: "「如果明天是好天氣，我們就去公園。」應該怎麼說？", options: ["If it will be sunny tomorrow, we will go to the park.", "If it was sunny tomorrow, we go to the park.", "If it is sunny tomorrow, we will go to the park.", "If it sunny tomorrow, we will go to the park."], answer: 2, hints: ["if 子句講未來要用現在式", "主要子句才用 will"], explanation: "if 子句用現在式 is，主要子句用 will go；if 子句不能用 will。" },
    { id: "jh-eng-conjunction-3", prompt: "「當我打電話給他時，他正在睡覺。」應該怎麼說？", options: ["When I call him, he sleeps.", "If I called him, he was sleeping.", "Because I called him, he was sleeping.", "When I called him, he was sleeping."], answer: 3, hints: ["時間用 when", "兩個動作都在過去，一個正在進行"], explanation: "時間子句用 when；他當時正在睡，用過去進行式 was sleeping." },
    { id: "jh-eng-conjunction-4", prompt: "副詞子句放在句首時，後面要加什麼？", options: ["逗號", "句號", "問號", "什麼都不用加"], answer: 0, hints: ["看看課本例句的標點", "子句在句首要跟主要子句分開"], explanation: "副詞子句放句首時，後面要加逗號，例如 When I got home, my mother was cooking." },
    { id: "jh-eng-conjunction-5", prompt: "下列哪一句是錯誤的？", options: ["If you are free, please call me.", "Because he was tired, so he went to bed early.", "When I was young, I lived in Kaohsiung.", "I stayed home because it was raining."], answer: 1, hints: ["注意 because 已經含有「所以」的意思", "找那個同時用了兩個連接詞的句子"], explanation: "because 與 so 不能同時使用，應改為 Because he was tired, he went to bed early." },
    { id: "jh-eng-conjunction-6", prompt: "「___ I was a child, I lived in Kaohsiung.」空格應填入？", options: ["If", "Because", "When", "Which"], answer: 2, hints: ["這是「當我還是小孩時」的時間", "時間用 when"], explanation: "描述過去某個時間點的狀態，用 when 引導時間子句。" },
    { id: "jh-eng-conjunction-7", prompt: "「He stayed at home ___ he was sick.」空格應填入？", options: ["when", "if", "which", "because"], answer: 3, hints: ["生病是待在家的原因", "原因用 because"], explanation: "生病是待在家的原因，用 because 引導原因子句。" },
  ],
};

const JH_ENG_READING: OnionLesson = {
  id: "jh-eng-reading-skill",
  title: "閱讀測驗技巧：先找主題句",
  subject: "英語",
  topic: "閱讀理解技巧",
  grade: "九上",
  stages: ["國中"],
  desc: "看不懂全部單字也能答題：先讀題目、再找主題句與關鍵字，答案通常就在那兩句附近。",
  takeaways: ["先讀題目再看文章，知道要找什麼", "主題句常在段首或段尾", "問句裡的字詞就是關鍵字，回文章定位它", "只選文章有依據的答案；過度推論或無中生有都不選"],
  frames: [
    { step: "步驟 1：不要從第一個字讀", id: 1, caption: "閱讀測驗最有效的方法，不是逐字把文章唸完，而是先看題目到底在問什麼。", action: "wave", prop: { kind: "flow", steps: ["先讀題目", "再讀文章", "回文章找答案"], active: 0 }, duration: 3400 },
    { step: "步驟 2：主題句在哪裡", id: 2, caption: "每段通常有一句主題句說明這段在講什麼，最常出現在段首，有時也放在段尾。", action: "point", prop: { kind: "text", text: "主題句：段首或段尾", sub: "其餘句子都在支持這一句", tone: "ok" }, duration: 3400 },
    { step: "步驟 3：用關鍵字定位", id: 3, caption: "題目問 When did Tom start playing the piano？，你就回文章找 Tom、piano 和時間這幾個字。", ask: { prompt: "題目問某件事發生的「時間」，回文章時最該注意什麼？", options: ["數字與時間詞（in 2019、last year）", "形容詞", "標點符號", "句子的長度"], answer: 0, hint: "問時間就找時間的線索。" }, action: "think", prop: { kind: "flow", steps: ["題目關鍵字", "回文章定位", "讀前後一句"], active: 1 }, duration: 3600 },
    { step: "步驟 4：優先找專有資訊", id: 4, caption: "人名、數字、時間、地名字母大寫或特別醒目，回文章一眼就看到，是最好用的定位線索。", action: "point", prop: { kind: "balance", left: "人名 / 地名字母大寫", right: "數字 / 時間最好認", tip: "這些詞最容易定位" }, duration: 3400 },
    { step: "步驟 5：上下文猜生字", id: 5, caption: "遇到生字別慌，看它前後的字去猜：The weather was chilly, so I wore a coat，chilly 大概就是很冷。", action: "walk", prop: { kind: "text", text: "The weather was chilly, so I wore a coat.", sub: "從「穿外套」回推 chilly ＝ 冷", tone: "ok" }, duration: 3600 },
    { step: "步驟 6：轉折詞是重點", id: 6, caption: "but、however 後面常是作者真正的意思；because、so 則帶出原因跟結果，要讀仔細。", ask: { prompt: "「I like the city, but the traffic is terrible.」作者對交通的看法是？", options: ["很喜歡", "覺得很糟", "沒有意見", "覺得很方便"], answer: 1, hint: "but 後面的才是轉折後的重點。" }, action: "jump", prop: { kind: "text", text: "but / however → 轉折後是重點", sub: "because / so → 原因與結果", tone: "ok" }, duration: 3600 },
    { step: "步驟 7：綜合演練一段", id: 7, caption: "綜合練一次：先找關鍵字定位，再把選項跟文章裡的句子一句一句比對。", ask: { prompt: "文章說「Tom started piano in 2019」，題目問何時開始，答案是？", options: ["In 2019", "In 2020", "When he was born", "沒提到"], answer: 0, hint: "回文章找 Tom 與 piano，旁邊的時間就是答案。" }, action: "think", prop: { kind: "flow", steps: ["找 Tom / piano", "看旁邊時間", "對照選項"], active: 2 }, duration: 3800 },
    { step: "步驟 8：認出選項的陷阱", id: 8, caption: "小心選項的陷阱：出現文章裡的字，不代表意思一樣，一定要選文章真的這樣說的。", action: "point", prop: { kind: "text", text: "只選文章真的說過的", sub: "有出現同一個字不代表答案正確", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：口訣收束", id: 9, caption: "口訣：先題目、再文章，主題句在頭尾，關鍵字定位、上下文猜字、轉折後是重點。預備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "jh-eng-reading-skill-1", prompt: "做英語閱讀測驗時，最有效的第一步是？", options: ["把文章每個單字都查完", "先讀題目，知道要找什麼", "先看選項的長度", "從最後一段倒著讀"], answer: 1, hints: ["帶著問題讀文章最有效率", "先知道要找什麼才不會白讀"], explanation: "先讀題目可以設定閱讀目標，回文章時更容易定位答案，不必逐字查單字。" },
    { id: "jh-eng-reading-skill-2", prompt: "「主題句」最常出現在哪裡？", options: ["標題裡", "一定是第二句", "段首或段尾", "不會出現在文章裡"], answer: 2, hints: ["它說明整段要講什麼", "作者通常會先講重點或最後總結"], explanation: "主題句說明整段主旨，最常出現在段首，也可能放在段尾作總結。" },
    { id: "jh-eng-reading-skill-3", prompt: "「The soup was bland, so I added some salt.」bland 最可能是什麼意思？", options: ["很辣", "很燙", "很好吃", "沒有味道"], answer: 3, hints: ["加了鹽代表原本的味道不足", "從動作回推形容詞"], explanation: "因為加了鹽，可推測 bland 是「沒味道、清淡」，需要加鹽才好喝。" },
    { id: "jh-eng-reading-skill-4", prompt: "「I wanted to go out, but it was raining hard.」作者最後怎麼了？", options: ["留在家裡", "出門了", "去買傘", "沒提到"], answer: 0, hints: ["but 後面的才是實際情況", "下大雨通常不會出門"], explanation: "but 之後說雨下得很大，可推知作者沒有出門、留在家裡。" },
    { id: "jh-eng-reading-skill-5", prompt: "選項裡出現文章提過的字，就一定是答案嗎？", options: ["一定對", "不一定，要看整句意思是否與文章一致", "一定錯", "只要字一樣就對"], answer: 1, hints: ["出題者常用同字陷阱", "要讀完整句再判斷"], explanation: "常見陷阱是把文章的字放進選項但改變意思，必須確認整句與文章相符。" },
    { id: "jh-eng-reading-skill-6", prompt: "題目問「Where did Tom go on Sunday?」回文章最該找哪一類線索？", options: ["形容詞", "標點", "地點名詞（on the beach / park）", "標題長度"], answer: 2, hints: ["問 Where 就找地點", "地名字母大寫最好認"], explanation: "Where 問地點，回文章找地名或地方名詞即可，形容詞和標點幫不上忙。" },
    { id: "jh-eng-reading-skill-7", prompt: "下列哪一種答案「最不該選」？", options: ["文章明說的事", "主題句支持的推論", "轉折後作者真正的看法", "用文章同一個字、但意思被改的選項"], answer: 3, hints: ["這是常見陷阱", "字一樣≠答案對"], explanation: "選項用文章原字卻改變意思，是典型同字陷阱；只選文章真的說過的。" },
  ],
};

const JH_ENG_EMAIL: OnionLesson = {
  id: "jh-eng-email",
  title: "英文書信與 e-mail",
  subject: "英語",
  topic: "書信與 e-mail 寫作",
  grade: "九下",
  stages: ["國中"],
  desc: "寫英文信有固定格式：稱謂、開頭問候、正文、結尾、署名。順序對了，看起來就專業。",
  takeaways: ["稱謂：Dear ＋ 名字，後面用逗號", "結尾：Best regards / Sincerely，再署名", "正文分段：一件事一段，不要全部擠在一起", "正式內文常用 I am writing to…；寄信前自查稱謂逗號、分段、署名三件事"],
  frames: [
    { step: "步驟 1：信有五個部分", id: 1, caption: "一封英文 e-mail 有固定的小結構：稱謂、開頭問候、正文、結尾、署名，一共五個部分。", action: "wave", prop: { kind: "flow", steps: ["稱謂", "開頭問候", "正文", "結尾", "署名"], active: 0 }, duration: 3600 },
    { step: "步驟 2：稱謂怎麼寫", id: 2, caption: "認識的人寫 Dear Amy, 不確定對方是誰就寫 Dear Sir or Madam, 後面千萬別忘了逗號。", action: "point", prop: { kind: "text", text: "Dear Amy,", sub: "不確定對象：Dear Sir or Madam,", tone: "ok" }, duration: 3400 },
    { step: "步驟 3：開頭先問好", id: 3, caption: "開頭先自然問候一句：How are you? 或 I hope you are doing well，再接著說明寫信目的。", ask: { prompt: "英文 e-mail 的開頭，哪一句最合適？", options: ["How are you?", "I am a student.", "Goodbye.", "Please reply."], answer: 0, hint: "開頭通常先問候對方。" }, action: "think", prop: { kind: "text", text: "How are you?", sub: "或 I hope you are doing well.", tone: "ok" }, duration: 3600 },
    { step: "步驟 4：內文常用句型", id: 4, caption: "正式信內文常用這兩個句型：I am writing to ask…，以及 I would like to…，直接又得體。", action: "point", prop: { kind: "text", text: "I am writing to ask…", sub: "I would like to…", tone: "ok" }, duration: 3400 },
    { step: "步驟 5：正文一件事一段", id: 5, caption: "正文把事情分段寫：先說明來意，再補充細節，最後提出請求或問題，別全部擠一段。", action: "walk", prop: { kind: "flow", steps: ["說明來意", "補充細節", "提出請求"], active: 1 }, duration: 3400 },
    { step: "步驟 6：結尾與署名", id: 6, caption: "結尾用 Best regards, 或 Sincerely, 下一行再寫自己的名字，順序不能顛倒。", ask: { prompt: "下列哪一個是合適的結尾？", options: ["Dear Amy,", "Best regards,", "Hello!", "How are you?"], answer: 1, hint: "結尾要能接上署名。" }, action: "jump", prop: { kind: "text", text: "Best regards,", sub: "下一行署名：Kevin", tone: "ok" }, duration: 3600 },
    { step: "步驟 7：實戰找一封信的錯", id: 7, caption: "實戰改錯：草稿常同時有稱謂缺逗號、全文擠一段、結尾亂用 Dear，一次修乾淨。", ask: { prompt: "「Dear Amy」後面忘了標點，正確應改成？", options: ["Dear Amy,", "Dear Amy。", "Dear Amy!", "Dear Amy；"], answer: 0, hint: "英文書信稱謂後用逗號。" }, action: "think", prop: { kind: "balance", left: "稱謂：Dear Amy,", right: "正文分段、署名", tip: "寄前自查三件事" }, duration: 3800 },
    { step: "步驟 8：提醒常見的錯", id: 8, caption: "寄之前自己檢查三件事：稱謂後有逗號、正文有分段、最後有署名，這三個最常漏。", action: "point", prop: { kind: "text", text: "✗ Dear Amy（少了逗號）", sub: "✓ Dear Amy,", tone: "warn" }, duration: 3400 },
    { step: "步驟 9：口訣收束", id: 9, caption: "口訣：稱謂、問候、正文、結尾、署名，五段到位；一件事一段，最後別忘記署名。預備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "jh-eng-email-1", prompt: "英文 e-mail 的稱謂「Dear Amy」後面應該加什麼？", options: ["句號", "逗號", "問號", "什麼都不加"], answer: 1, hints: ["這是書信的固定格式", "後面接著正文，需要停頓"], explanation: "稱謂後面要加逗號，寫成 Dear Amy,；句號、問號都不是書稱謂的標點。" },
    { id: "jh-eng-email-2", prompt: "下列哪一個順序是英文書信的正確結構？", options: ["署名 → 稱謂 → 正文", "正文 → 稱謂 → 結尾", "稱謂 → 開頭問候 → 正文 → 結尾 → 署名", "稱謂 → 署名 → 正文"], answer: 2, hints: ["先稱呼對方，再問候、說明事情", "最後才簽名"], explanation: "正確順序是稱謂、開頭問候、正文、結尾、署名，署名永遠在最後。" },
    { id: "jh-eng-email-3", prompt: "信末要結束時，下列哪一句最合適？", options: ["Dear Tom,", "How are you?", "I am fine.", "Best regards,"], answer: 3, hints: ["結尾語要能接上署名", "Dear 是稱謂，不是結尾"], explanation: "Best regards, 是常見的結尾語，後面接署名；Dear Tom, 是開頭的稱謂。" },
    { id: "jh-eng-email-4", prompt: "寫 e-mail 給不確定是誰的對象，稱謂最好寫？", options: ["Dear Sir or Madam,", "Dear you,", "Dear friend,", "Hi, 沒有稱謂"], answer: 0, hints: ["不知道對方姓名時的正式寫法", "Sir 與 Madam 分別指先生與女士"], explanation: "不確定收件者時用 Dear Sir or Madam, 最得體；Dear you、Dear friend 都不正式。" },
    { id: "jh-eng-email-5", prompt: "關於 e-mail 正文，下列哪一個建議最好？", options: ["全部擠成一大段最省事", "一件事一段，先說明來意再補充細節", "只寫一個字就好", "不要分段，段落是給作文用的"], answer: 1, hints: ["分段讓對方好讀", "先講目的再看細節"], explanation: "正文應該分段，先說明來意、再補充細節、最後提出請求，對方才好讀。" },
    { id: "jh-eng-email-6", prompt: "正式 e-mail 內文要說明寫信目的，哪一句最合適？", options: ["What's up?", "Hey dude.", "I am writing to ask about the meeting.", "Bye."], answer: 2, hints: ["正式內文常用 I am writing to…", "其他選項太隨便"], explanation: "正式 e-mail 用 I am writing to… 說明來意，得體清楚；What's up、Hey dude 太口語。" },
    { id: "jh-eng-email-7", prompt: "下列哪一封 e-mail 有「格式錯誤」？", options: ["Dear Amy, / How are you? / Best regards, / Kevin", "Dear Sir or Madam, / I am writing to… / Yours truly, / Lisa", "Dear Tom, / Thank you for your help. / Best, / Bob", "Dear Amy / How are you? / Best regards, / Kevin"], answer: 3, hints: ["找稱謂少了逗號的那封", "Dear Amy 後面要加逗號"], explanation: "「Dear Amy」後面忘了逗號，是常見格式錯誤；其餘三封格式都正確。" },
  ],
};

export default [
  JH_ENG_PAST,
  JH_ENG_FUTURE,
  JH_ENG_COMPARATIVE,
  JH_ENG_GERUND,
  JH_ENG_RELATIVE,
  JH_ENG_CONJUNCTION,
  JH_ENG_READING,
  JH_ENG_EMAIL,
];
