/**
 * 高中數學課程（洋蔥學院 200 堂擴充計畫：三、高中新增 65 堂／數學 10 堂）。
 *
 * 高中內容的設計原則：每一堂都從「為什麼要學這個」開始，
 * 把定義拆成看得見的步驟，最後收在一個能帶走的判斷準則。
 */
import type { OnionLesson } from "@/game/onionAcademyLessons";

const SH_MATH_POLYNOMIAL: OnionLesson = {
  id: "sh-math-polynomial",
  title: "多項式函數：次數決定長相",
  subject: "數學",
  topic: "多項式函數",
  grade: "高一",
  stages: ["高中"],
  desc: "多項式的次數決定圖形長什麼樣：一次是直線、二次是拋物線、三次會轉兩個彎。",
  takeaways: ["次數＝最高次項的指數，決定圖形的基本形狀", "係數正負決定圖形的開口或兩端方向", "因式定理：f(a)＝0 代表（x−a）是因式", "領導係數的正負還決定圖形兩端延伸方向；多項式加減只能同次項合併"],
  frames: [
    { step: "步驟 1：先看次數", id: 1, caption: "嗨！拿到一個多項式，第一件事是看它的「次數」：x 的最高次方是幾次，它就是幾次多項式。", action: "wave", prop: { kind: "text", text: "f(x) ＝ 2x³ − 5x² ＋ x − 7", sub: "最高次是 3 次 → 三次多項式", tone: "ok" }, duration: 3400 },
    { step: "步驟 2：多項式為什麼到處都用", id: 2, caption: "自由落體的高度、工廠的利潤、人口的成長，很多現象都能用多項式來近似描述——它是最常用的數學模型。", action: "point", prop: { kind: "text", text: "h(t)、P(x)、N(t) 常是多項式", sub: "用一個式子逼近現實變化", tone: "ok" }, duration: 3400 },
    { step: "步驟 3：次數決定圖形", id: 3, caption: "一次函數是斜直線、二次函數是拋物線、三次函數會轉兩個彎，次數越高越會「扭」。", action: "point", prop: { kind: "flow", steps: ["一次：直線", "二次：拋物線", "三次：兩個彎"], active: 1 }, duration: 3400 },
    { step: "步驟 4：係數決定方向", id: 4, caption: "最高次項的係數正負，決定圖形往哪邊跑：二次係數是正，開口向上；是負，開口向下。", ask: { prompt: "f(x) ＝ −3x² ＋ 2x ＋ 1 的圖形開口方向是？", options: ["開口向上", "開口向下", "是一條直線", "沒有開口"], answer: 1, hint: "看最高次項 −3x² 的係數是正的還是負的。" }, action: "think", prop: { kind: "text", text: "x² 係數 ＞ 0 → 開口向上", sub: "x² 係數 ＜ 0 → 開口向下", tone: "ok" }, duration: 3600 },
    { step: "步驟 5：多項式的值怎麼算", id: 5, caption: "要算 f(2)：把每一個 x 都換成 2，再乘開相加：2×8 − 5×4 ＋ 2 − 7 ＝ −9。", action: "walk", prop: { kind: "text", text: "f(2) ＝ 16 − 20 ＋ 2 − 7 ＝ −9", sub: "把 x 換成 2，逐項算再相加", tone: "ok" }, duration: 3800 },
    { step: "步驟 6：同次項才能合併", id: 6, caption: "多項式加減時，只有次數相同的項能合併：2x³ ＋ 3x³ ＝ 5x³；但 x³ 與 x² 次數不同，不能硬加在一起。", action: "walk", prop: { kind: "text", text: "（2x³ − 5x²）＋（x³ ＋ 2x²）", sub: "＝ 3x³ − 3x²（同次項合併）", tone: "ok" }, duration: 3600 },
    { step: "步驟 7：因式定理", id: 7, caption: "如果 f(a) ＝ 0，那麼（x − a）就是 f(x) 的因式；反過來也是。這是找根最有力的工具。", ask: { prompt: "若 f(3) ＝ 0，下列哪一個一定是 f(x) 的因式？", options: ["x ＋ 3", "x − 3", "3x − 1", "x"], answer: 1, hint: "使多項式為 0 的那個數，就是因式（x − 那個數）。" }, action: "jump", prop: { kind: "balance", left: "f(3) ＝ 0", right: "（x − 3）是因式", tip: "因式定理：值為 0 就代表整除" }, duration: 3800 },
    { step: "步驟 8：除法與餘式", id: 8, caption: "把 f(x) 除以（x − a），餘式正好等於 f(a)——這就是餘式定理，可以省下整個長除法。", action: "point", prop: { kind: "flow", steps: ["除以（x − a）", "餘式 ＝ f(a)", "若餘 0 → 整除"], active: 1 }, duration: 3600 },
    { step: "步驟 9：端點行為看領導係數", id: 9, caption: "再深入一層：領導係數除了開口，還決定圖形兩端往哪伸。三次領導係數為正時，x 很大的右端往上跑。", ask: { prompt: "f(x) ＝ x³ − 2x，當 x 很大（往右）時，圖形往哪邊去？", options: ["往上", "往下", "保持水平", "上下震動"], answer: 0, hint: "領導係數是 1 為正，x 很大時 x³ 主導 → 往上。" }, action: "jump", prop: { kind: "text", text: "領導係數 ＋ → 右端往上", sub: "奇次且為正：左端往下、右端往上", tone: "ok" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：先看次數定形狀、再看係數定方向；要驗根就用因式定理代進去。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-polynomial-1", prompt: "多項式 f(x) ＝ 4x⁵ − x³ ＋ 2 是幾次多項式？", options: ["3 次", "4 次", "5 次", "6 次"], answer: 2, hints: ["看最高次的 x", "x⁵ 的指數就是次數"], explanation: "最高次項是 4x⁵，指數 5，所以是 5 次多項式。" },
    { id: "sh-math-polynomial-2", prompt: "f(x) ＝ x² − 4x ＋ 3，則 f(2) 等於多少？", options: ["−1", "0", "1", "3"], answer: 0, hints: ["把 x 全部換成 2", "4 − 8 ＋ 3 ＝ ?"], explanation: "f(2) ＝ 2² − 4×2 ＋ 3 ＝ 4 − 8 ＋ 3 ＝ −1。" },
    { id: "sh-math-polynomial-3", prompt: "若 f(−1) ＝ 0，則下列何者為 f(x) 的因式？", options: ["x − 1", "x ＋ 1", "x", "x² ＋ 1"], answer: 1, hints: ["因式定理：f(a) ＝ 0 →（x − a）是因式", "這裡的 a 是 −1"], explanation: "f(−1) ＝ 0 表示（x −（−1））＝（x ＋ 1）是因式。" },
    { id: "sh-math-polynomial-4", prompt: "三次多項式的圖形最多會有幾個「轉彎」（極值）？", options: ["0 個", "1 個", "2 個", "3 個"], answer: 2, hints: ["二次拋物線有 1 個轉彎", "次數每多一次，最多多一個轉彎"], explanation: "三次函數最多有 2 個極值（轉彎處）。" },
    { id: "sh-math-polynomial-5", prompt: "f(x) ＝ −2x² ＋ 6x − 1 的圖形，下列敘述何者正確？", options: ["開口向上且有最大值", "開口向下且有最大值", "開口向下且有最小值", "是一條直線"], answer: 1, hints: ["x² 係數是 −2，是負的", "開口向下時，頂點是最高點"], explanation: "二次項係數為負，開口向下，頂點是最高點，因此有最大值。" },
    { id: "sh-math-polynomial-6", prompt: "f(x) ＝ x³ − 4x，則 f(2) 等於多少？", options: ["0", "8", "−8", "4"], answer: 0, hints: ["把每個 x 都換成 2", "2³ − 4×2 ＝ 8 − 8"], explanation: "f(2) ＝ 8 − 8 ＝ 0；既然 f(2)＝0，代表（x−2）一定是因式。" },
    { id: "sh-math-polynomial-7", prompt: "關於 f(x) ＝ −x³ ＋ 1，下列敘述何者正確？", options: ["是二次拋物線", "是三次，x 很大時右端往下", "是三次，x 很大時右端往上", "它沒有領導係數"], answer: 1, hints: ["最高次是 −x³，係數為負", "x 很大時 −x³ 會趨近負無窮"], explanation: "最高次 −x³ 是三次；領導係數為負，x 很大時圖形右端往下跑。" },
  ],
};

const SH_MATH_EXP_LOG: OnionLesson = {
  id: "sh-math-exp-log",
  title: "指數與對數：一體兩面",
  subject: "數學",
  topic: "指數與對數",
  grade: "高一",
  stages: ["高中"],
  desc: "指數問「幾個底相乘」，對數問「要乘幾次」。看懂這層互逆關係，log 就不再是背公式。",
  takeaways: ["aⁿ 表示 a 連乘 n 次；a⁰ ＝ 1、a⁻ⁿ ＝ 1/aⁿ", "log_a b ＝ n 代表 aⁿ ＝ b（指數與對數互逆）", "運算：log(MN) ＝ logM ＋ logN、log(M/N) ＝ logM − logN", "對數的真數必須為正、底數為正且不等於 1；解對數式先翻回指數"],
  frames: [
    { step: "步驟 1：指數在問什麼", id: 1, caption: "嗨！2⁵ 是什麼意思？答案是 2 連乘 5 次：2³ 是 8、2⁵ 是 32。指數就是「乘幾次」。", action: "wave", prop: { kind: "bars", items: [{ label: "2³", value: 8 }, { label: "2⁵", value: 32 }], unit: "", active: 1 }, duration: 3600 },
    { step: "步驟 2：生活裡的指數與對數", id: 2, caption: "細菌每小時變成 2 倍、聲音的分貝、地震的芮氏規模，都是對數尺度——它專門處理「成長很快」或「範圍很大」的量。", action: "point", prop: { kind: "text", text: "分貝、芮氏規模都是對數", sub: "把巨大範圍壓成好談的數字", tone: "ok" }, duration: 3600 },
    { step: "步驟 3：指數律", id: 3, caption: "指數律：同底相乘指數相加、相除指數相減、乘方指數相乘。2³ × 2⁴ ＝ 2⁷。", action: "point", prop: { kind: "text", text: "2³ × 2⁴ ＝ 2³⁺⁴ ＝ 2⁷", sub: "同底相乘 → 指數相加", tone: "ok" }, duration: 3400 },
    { step: "步驟 4：負指數與零次方", id: 4, caption: "2⁰ ＝ 1（任何非零數的零次方都是 1）、2⁻³ ＝ 1/8，負指數代表倒數。", ask: { prompt: "2⁻² 等於多少？", options: ["−4", "−1/4", "1/4", "4"], answer: 2, hint: "負指數就是取倒數：2⁻² ＝ 1/2²。" }, action: "think", prop: { kind: "text", text: "2⁻³ ＝ 1/2³ ＝ 1/8", sub: "負指數 ＝ 倒數；2⁰ ＝ 1", tone: "ok" }, duration: 3600 },
    { step: "步驟 5：對數是反過來問", id: 5, caption: "對數問的是「要乘幾次」：log₂ 32 ＝ 5，因為 2 連乘 5 次得到 32。", action: "walk", prop: { kind: "balance", left: "2⁵ ＝ 32", right: "log₂ 32 ＝ 5", tip: "指數與對數是同一件事的兩種問法" }, duration: 3800 },
    { step: "步驟 6：對數律", id: 6, caption: "對數把乘法變成加法：log(MN) ＝ logM ＋ logN；除法變減法；次方可以搬到前面。", ask: { prompt: "log₂ 8 ＋ log₂ 4 等於多少？", options: ["log₂ 12", "5", "32", "2"], answer: 1, hint: "log₂8 ＝ 3、log₂4 ＝ 2，相加就是答案（也等於 log₂32）。" }, action: "jump", prop: { kind: "text", text: "log(MN) ＝ logM ＋ logN", sub: "log₂8 ＋ log₂4 ＝ 3 ＋ 2 ＝ 5", tone: "ok" }, duration: 3800 },
    { step: "步驟 7：次方可以搬到前面", id: 7, caption: "對數律的第三招：log(xⁿ) ＝ n·log x，次方 n 可以搬到 log 前面變乘數，這是解指數方程式的關鍵一步。", action: "point", prop: { kind: "text", text: "log₂ 2³ ＝ 3 log₂ 2 ＝ 3", sub: "次方搬到前面當乘數", tone: "ok" }, duration: 3600 },
    { step: "步驟 8：換底與常用對數", id: 8, caption: "計算機上的 log 是常用的 10 為底。要換底就用 log_a b ＝ log b ÷ log a。", action: "point", prop: { kind: "flow", steps: ["log_a b", "＝ log b ÷ log a", "常用底：10"], active: 1 }, duration: 3400 },
    { step: "步驟 9：對數的合法性條件", id: 9, caption: "不是什麼都能取 log：真數必須大於 0、底數必須為正且不等於 1。踩進這條線，式子就沒有意義。", ask: { prompt: "log₂ (x − 1) 有意義時，x 必須滿足？", options: ["x ＞ 1", "x ＜ 1", "x ＝ 1", "x 可以是任何數"], answer: 0, hint: "對數的真數必須是正數：x − 1 ＞ 0。" }, action: "think", prop: { kind: "text", text: "真數 ＞ 0、底 ＞ 0 且 ≠ 1", sub: "其餘寫法都無意義", tone: "warn" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：指數問「乘幾次」、對數問「要乘幾次才得到」；看到 log 就翻回指數來看。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-exp-log-1", prompt: "3⁴ 等於多少？", options: ["12", "27", "81", "64"], answer: 2, hints: ["3 連乘 4 次", "3×3 ＝ 9，再乘 3 再乘 3"], explanation: "3⁴ ＝ 3×3×3×3 ＝ 81。" },
    { id: "sh-math-exp-log-2", prompt: "log₃ 27 等於多少？", options: ["3", "9", "27", "1/3"], answer: 0, hints: ["問「3 要乘幾次才得到 27」", "3³ ＝ 27"], explanation: "因為 3³ ＝ 27，所以 log₃ 27 ＝ 3。" },
    { id: "sh-math-exp-log-3", prompt: "log₂ 8 ＋ log₂ 4 等於多少？", options: ["5", "log₂ 12", "32", "2"], answer: 0, hints: ["log₂8 ＝ 3、log₂4 ＝ 2", "相加就是 5（也等於 log₂32）"], explanation: "log₂ 8 ＝ 3、log₂ 4 ＝ 2，相加得 5，也就是 log₂ 32。" },
    { id: "sh-math-exp-log-4", prompt: "下列何者等於 1？", options: ["5⁰", "0⁰", "log₂ 1", "log₅ 0"], answer: 0, hints: ["任何非零數的零次方都是 1", "log₂1 ＝ 0，不是 1"], explanation: "5⁰ ＝ 1；log₂1 ＝ 0、log₅0 無意義、0⁰ 無定義。" },
    { id: "sh-math-exp-log-5", prompt: "若 log_a b ＝ n，則下列關係何者正確？", options: ["aⁿ ＝ b", "bⁿ ＝ a", "a ＋ b ＝ n", "a × b ＝ n"], answer: 0, hints: ["把對數翻回指數的寫法", "底數的 n 次方等於真數"], explanation: "對數的定義就是 log_a b ＝ n ⟺ aⁿ ＝ b。" },
    { id: "sh-math-exp-log-6", prompt: "log₂ x ＝ 4，則 x 等於多少？", options: ["8", "16", "2", "4"], answer: 1, hints: ["把對數翻回指數", "x ＝ 2⁴"], explanation: "log₂ x ＝ 4 翻回指數式就是 x ＝ 2⁴ ＝ 16。" },
    { id: "sh-math-exp-log-7", prompt: "下列哪一個對數式「無意義」（不能算）？", options: ["log₂ 8", "log₃ 1", "log₂ (−4)", "log₅ 5"], answer: 2, hints: ["對數的真數必須是正數", "−4 是負數"], explanation: "log 的真數必須大於 0，log₂(−4) 無意義；其他真數 8、1、5 都為正，皆有意義。" },
  ],
};

const SH_MATH_TRIG: OnionLesson = {
  id: "sh-math-trig",
  title: "三角函數：從直角三角形出發",
  subject: "數學",
  topic: "三角函數",
  grade: "高二",
  stages: ["高中"],
  desc: "sin、cos、tan 只是「邊的比值」。先從直角三角形記住定義，再談廣義角與正弦定理。",
  takeaways: ["sin ＝ 對邊/斜邊、cos ＝ 鄰邊/斜邊、tan ＝ 對邊/鄰邊", "廣義角用單位圓定義，正負號看象限", "正弦定理：a/sinA ＝ b/sinB ＝ c/sinC", "先判斷是否直角、用畢氏定理補出第三邊，再依「對誰除以誰」帶入比值"],
  frames: [
    { step: "步驟 1：先記三個比值", id: 1, caption: "嗨！直角三角形裡，同一個角的三組邊比永遠固定，這就是 sin、cos、tan 的定義。", action: "wave", prop: { kind: "shape", shape: "triangle", base: 4, height: 3, label: "直角三角形：鄰邊 4、對邊 3、斜邊 5" }, duration: 3600 },
    { step: "步驟 2：三角為什麼重要", id: 2, caption: "測量山高、建築斜率、航海定位，都不能真的爬上量——只要知道一邊與一個角，三角函數就能把其餘邊角算出來。", action: "point", prop: { kind: "text", text: "測山高、算斜率、航海定位", sub: "不用爬上去也能算距離", tone: "ok" }, duration: 3600 },
    { step: "步驟 3：定義寫下來", id: 3, caption: "對邊比斜邊是 sin、鄰邊比斜邊是 cos、對邊比鄰邊是 tan。先被「比值」而不是「長度」。", action: "point", prop: { kind: "text", text: "sin ＝ 對邊/斜邊、cos ＝ 鄰邊/斜邊", sub: "tan ＝ 對邊/鄰邊", tone: "ok" }, duration: 3400 },
    { step: "步驟 4：算一次看看", id: 4, caption: "鄰邊 4、對邊 3、斜邊 5 的三角形：sin ＝ 3/5、cos ＝ 4/5、tan ＝ 3/4。", ask: { prompt: "直角三角形中，對邊 3、鄰邊 4、斜邊 5，則 sin 等於？", options: ["3/5", "4/5", "3/4", "5/3"], answer: 0, hint: "sin 是對邊除以斜邊。" }, action: "think", prop: { kind: "shape", shape: "triangle", base: 4, height: 3, label: "sin ＝ 3/5、cos ＝ 4/5、tan ＝ 3/4" }, duration: 3800 },
    { step: "步驟 5：特別角要背", id: 5, caption: "30°、45°、60° 的比值要熟：sin30° ＝ 1/2、sin45° ＝ √2/2、sin60° ＝ √3/2。", action: "walk", prop: { kind: "text", text: "sin30° ＝ 1/2、sin45° ＝ √2/2、sin60° ＝ √3/2", sub: "cos 反著記、tan45° ＝ 1", tone: "ok" }, duration: 3800 },
    { step: "步驟 6：先用畢氏定理補邊", id: 6, caption: "題目常只給兩股、沒給斜邊：先用畢氏定理補出來。已知股 3、股 4，斜邊 ＝ √（9 ＋ 16）＝ 5。", action: "point", prop: { kind: "text", text: "斜邊 ＝ √（3² ＋ 4²）＝ √25 ＝ 5", sub: "缺斜邊就先用畢氏定理", tone: "ok" }, duration: 3600 },
    { step: "步驟 7：用單位圓看正負", id: 7, caption: "把角放到單位圓上，座標就是（cos, sin）：第二象限 x 負 y 正，所以 cos 負、sin 正。", ask: { prompt: "120° 的 sin 值與 cos 值正負為何？", options: ["sin 正、cos 正", "sin 正、cos 負", "sin 負、cos 正", "sin 負、cos 負"], answer: 1, hint: "120° 在第二象限，x 為負、y 為正。" }, action: "jump", prop: { kind: "text", text: "第二象限：x 負、y 正", sub: "cos ＜ 0、sin ＞ 0", tone: "ok" }, duration: 3600 },
    { step: "步驟 8：正弦定理", id: 8, caption: "不是直角三角形也能算：a/sinA ＝ b/sinB ＝ c/sinC，等於外接圓直徑的兩倍。", action: "point", prop: { kind: "text", text: "a ÷ sinA ＝ b ÷ sinB ＝ c ÷ sinC", sub: "邊與其對角的正弦成正比" }, duration: 3800 },
    { step: "步驟 9：sin 和 cos 別記反", id: 9, caption: "記口訣避免混淆：sin 的分子永遠是「對邊」、cos 的分子永遠是「鄰邊」，跟角畫在左邊或右邊無關。", ask: { prompt: "直角三角形中，鄰邊 12、對邊 5、斜邊 13，則 cos 等於？", options: ["5/13", "12/13", "5/12", "12/5"], answer: 1, hint: "cos ＝ 鄰邊 ÷ 斜邊 ＝ 12 ÷ 13。" }, action: "think", prop: { kind: "text", text: "sin：對邊／斜邊；cos：鄰邊／斜邊", sub: "分子分別是「對」「鄰」，別記反", tone: "warn" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：先分清對邊、鄰邊、斜邊，比值只是「對誰除以誰」；正負號交給象限判斷。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-trig-1", prompt: "直角三角形中，對邊 6、鄰邊 8、斜邊 10，則 cos 等於？", options: ["6/10", "8/10", "6/8", "10/8"], answer: 1, hints: ["cos 是鄰邊除以斜邊", "鄰邊是 8、斜邊是 10"], explanation: "cos ＝ 鄰邊/斜邊 ＝ 8/10 ＝ 4/5。" },
    { id: "sh-math-trig-2", prompt: "sin30° 等於多少？", options: ["1/2", "√2/2", "√3/2", "1"], answer: 0, hints: ["特別角要記牢", "30-60-90 的邊比是 1 : √3 : 2"], explanation: "30° 的對邊是 1、斜邊是 2，sin30° ＝ 1/2。" },
    { id: "sh-math-trig-3", prompt: "150° 位在哪個象限？其 cos 值的正負為？", options: ["第一象限、正", "第二象限、負", "第三象限、負", "第四象限、正"], answer: 1, hints: ["90° 到 180° 之間是第二象限", "第二象限 x 是負的"], explanation: "150° 在第二象限，x 座標為負，所以 cos 為負。" },
    { id: "sh-math-trig-4", prompt: "正弦定理的內容是？", options: ["a ＋ b ＝ c", "a/sinA ＝ b/sinB ＝ c/sinC", "a×sinA ＝ b×sinB", "sinA ＋ sinB ＝ sinC"], answer: 1, hints: ["把每一邊除以它的對角的正弦", "這些比值都相等"], explanation: "正弦定理：a/sinA ＝ b/sinB ＝ c/sinC。" },
    { id: "sh-math-trig-5", prompt: "tan45° 等於多少？", options: ["0", "1/2", "1", "√3"], answer: 2, hints: ["45-45-90 的兩股一樣長", "tan 是對邊除以鄰邊"], explanation: "45° 時對邊與鄰邊相等，所以 tan45° ＝ 1。" },
    { id: "sh-math-trig-6", prompt: "直角三角形中，鄰邊 4、對邊 3、斜邊 5，則 tan 等於？", options: ["3/5", "4/5", "3/4", "4/3"], answer: 2, hints: ["tan ＝ 對邊 ÷ 鄰邊", "3 ÷ 4 等於多少"], explanation: "tan ＝ 對邊/鄰邊 ＝ 3/4。" },
    { id: "sh-math-trig-7", prompt: "已知 sinθ ＝ 1/2，且 θ 為銳角，則 cosθ 等於？", options: ["√3/2", "1/2", "√2/2", "1"], answer: 0, hints: ["sinθ＝1/2 表示 θ＝30°", "cos30° ＝ √3/2"], explanation: "sinθ＝1/2 對應特別角 30°，cos30°＝√3/2（也可用 cos²θ＝1−sin²θ 驗算）。" },
  ],
};

const SH_MATH_LINE_CIRCLE: OnionLesson = {
  id: "sh-math-line-circle",
  title: "直線與圓：距離決定關係",
  subject: "數學",
  topic: "直線與圓",
  grade: "高二",
  stages: ["高中"],
  desc: "圓與直線的關係只有三種：相交兩點、相切一點、不相交。關鍵是「圓心到直線的距離」。",
  takeaways: ["圓的標準式：（x−h）² ＋ （y−k）² ＝ r²，圓心（h, k）", "圓心到直線距離 d：d ＜ r 相交、d ＝ r 相切、d ＞ r 不相交", "切線垂直於圓心與切點連線", "先讀出圓心與半徑，再算 d 與 r 比較，一次判出交點數與切線數"],
  frames: [
    { step: "步驟 1：圓的方程式", id: 1, caption: "嗨！圓的標準式：（x − 3）² ＋ （y ＋ 2）² ＝ 25，代表圓心在（3, −2）、半徑是 5。", action: "wave", prop: { kind: "text", text: "（x − 3）² ＋ （y ＋ 2）² ＝ 25", sub: "圓心（3, −2）、半徑 5", tone: "ok" }, duration: 3800 },
    { step: "步驟 2：為什麼要分三種關係", id: 2, caption: "光學透鏡的成像、行星軌道與恆星是否交會，本質都是「圓與直線」碰不碰、碰幾點——所以要把距離算準。", action: "point", prop: { kind: "text", text: "透鏡成像、軌道交會", sub: "都是圓與直線的位置問題", tone: "ok" }, duration: 3600 },
    { step: "步驟 3：距離公式", id: 3, caption: "要把關係講清楚，得先會算「點到直線的距離」：把點代入直線方程式再除以係數平方和的開根號。", action: "point", prop: { kind: "text", text: "d ＝ |ax₀ ＋ by₀ ＋ c| ÷ √（a² ＋ b²）", sub: "分子帶絕對值，距離一定是正的", tone: "ok" }, duration: 3800 },
    { step: "步驟 4：距離公式帶數進去", id: 4, caption: "拿圓心（0,0）到直線 3x ＋ 4y − 10 ＝ 0 練一次：|0 ＋ 0 − 10| ÷ √（9 ＋ 16）＝ 10 ÷ 5 ＝ 2。", action: "walk", prop: { kind: "text", text: "d ＝ 10 ÷ 5 ＝ 2", sub: "分子 10、分母 √25 ＝ 5", tone: "ok" }, duration: 3800 },
    { step: "步驟 5：三種關係", id: 5, caption: "比較 d 與半徑 r：d 小於 r 是割線（交兩點）、d 等於 r 是切線（交一點）、d 大於 r 不相交。", ask: { prompt: "圓心到直線的距離剛好等於半徑，直線與圓的關係是？", options: ["相交兩點", "相切於一點", "不相交", "無法判斷"], answer: 1, hint: "距離等於半徑時，直線剛好碰到圓一個點。" }, action: "think", prop: { kind: "flow", steps: ["d ＜ r：交兩點", "d ＝ r：相切", "d ＞ r：不相交"], active: 1 }, duration: 3800 },
    { step: "步驟 6：切線的性質", id: 6, caption: "切線會垂直於「圓心到切點」的那條半徑，這是解切線問題的關鍵。", action: "walk", prop: { kind: "text", text: "切線 ⊥ 圓心到切點的連線", sub: "垂直 → 斜率相乘等於 −1", tone: "ok" }, duration: 3400 },
    { step: "步驟 7：斜率的角色", id: 7, caption: "兩直線垂直時，斜率相乘等於 −1：若半徑斜率是 2，切線斜率就是 −1/2。", ask: { prompt: "半徑的斜率是 3，則切線的斜率是？", options: ["3", "−3", "−1/3", "1/3"], answer: 2, hint: "垂直的兩條直線，斜率相乘等於 −1。" }, action: "jump", prop: { kind: "balance", left: "斜率 3", right: "切線斜率 −1/3", tip: "相乘 ＝ −1 就是垂直" }, duration: 3600 },
    { step: "步驟 8：常見作法", id: 8, caption: "求切線的標準流程：設切點 → 算半徑斜率 → 取負倒數得切線斜率 → 用點斜式寫出來。", action: "point", prop: { kind: "flow", steps: ["設切點", "算半徑斜率", "取負倒數", "點斜式寫出"], active: 2 }, duration: 3600 },
    { step: "步驟 9：用 d 與 r 數交點", id: 9, caption: "把 d 算出來再和 r 比大小，交點數就出來：d＜r 有 2 個、d＝r 有 1 個、d＞r 有 0 個。", ask: { prompt: "圓半徑 5，圓心到直線距離 3，直線與圓有幾個交點？", options: ["0 個", "1 個", "2 個", "3 個"], answer: 2, hint: "d＝3 比 r＝5 小，直線穿進圓裡。" }, action: "think", prop: { kind: "text", text: "d ＝ 3 ＜ r ＝ 5 → 2 個交點", sub: "d ＝ r 為 1 個、d ＞ r 為 0 個", tone: "ok" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：圓的問題幾乎都在比較「距離與半徑」；看到切線就先想垂直。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-line-circle-1", prompt: "圓（x − 2）² ＋ （y ＋ 1）² ＝ 9 的圓心與半徑是？", options: ["圓心（2, −1）、半徑 3", "圓心（−2, 1）、半徑 3", "圓心（2, −1）、半徑 9", "圓心（2, 1）、半徑 9"], answer: 0, hints: ["標準式裡是（x − h）² ＋ （y − k）²", "等號右邊是半徑的平方"], explanation: "圓心（2, −1），半徑平方是 9，所以半徑是 3。" },
    { id: "sh-math-line-circle-2", prompt: "圓心到直線的距離 d ＞ 半徑 r 時，直線與圓的關係是？", options: ["相交於兩點", "相切於一點", "不相交", "重疊"], answer: 2, hints: ["距離比半徑還遠", "直線完全在圓外"], explanation: "d ＞ r 表示直線在圓外，沒有交點。" },
    { id: "sh-math-line-circle-3", prompt: "切線與圓心的連線（到切點）有什麼關係？", options: ["平行", "垂直", "重合", "夾 45 度"], answer: 1, hints: ["這是切線最基本的性質", "垂直代表斜率相乘等於 −1"], explanation: "切線垂直於圓心與切點的連線。" },
    { id: "sh-math-line-circle-4", prompt: "半徑的斜率是 −2，則過該切點的切線斜率是？", options: ["−2", "2", "1/2", "−1/2"], answer: 2, hints: ["垂直 → 斜率相乘等於 −1", "−2 × ? ＝ −1"], explanation: "（−2）×（1/2）＝ −1，所以切線斜率是 1/2。" },
    { id: "sh-math-line-circle-5", prompt: "點（0, 0）到直線 3x ＋ 4y − 10 ＝ 0 的距離是？", options: ["1", "2", "5", "10"], answer: 1, hints: ["d ＝ |ax₀ ＋ by₀ ＋ c| ÷ √（a² ＋ b²）", "分母是 √（9 ＋ 16） ＝ 5"], explanation: "d ＝ |3×0 ＋ 4×0 − 10| ÷ √（3² ＋ 4²） ＝ 10 ÷ 5 ＝ 2。" },
    { id: "sh-math-line-circle-6", prompt: "圓心在（0,0）、半徑 5，直線 3x ＋ 4y − 25 ＝ 0 與圓的關係是？", options: ["相交兩點", "相切於一點", "不相交", "兩者重合"], answer: 1, hints: ["d ＝ |−25| ÷ √（9 ＋ 16）", "d ＝ 25 ÷ 5 ＝ 5 ＝ 半徑"], explanation: "d ＝ 25 ÷ 5 ＝ 5，正好等於半徑，故直線與圓相切於一點。" },
    { id: "sh-math-line-circle-7", prompt: "圓外一點（到圓心距離 5 ＞ 半徑 3），可作幾條切線？", options: ["0 條", "1 條", "2 條", "無限多條"], answer: 2, hints: ["點在圓外（距離大於半徑）", "圓外一點恰可畫出兩條切線"], explanation: "點在圓外時恰可作兩條切線；點在圓上只有一條、點在圓內沒有切線。" },
  ],
};

const SH_MATH_SEQUENCE: OnionLesson = {
  id: "sh-math-sequence",
  title: "數列與級數：規律的力量",
  subject: "數學",
  topic: "數列與級數",
  grade: "高二",
  stages: ["高中"],
  desc: "等差是「每次加同一個數」，等比是「每次乘同一個數」。把規律寫成公式，就能算很遠的項。",
  takeaways: ["等差：aₙ ＝ a₁ ＋ （n−1）d；和 Sₙ ＝ n（a₁＋aₙ）/2", "等比：aₙ ＝ a₁ · r^(n−1)；和 Sₙ ＝ a₁（rⁿ−1）/（r−1）", "無窮等比且 |r| ＜ 1 時，和收斂到 a₁/（1−r）", "套收斂公式前先檢查 |r|＜1；公比為負只是交錯，仍可收斂"],
  frames: [
    { step: "步驟 1：先看是加還是乘", id: 1, caption: "嗨！看數列的相鄰兩項：固定「加」同一個數是等差，固定「乘」同一個數是等比。", action: "wave", prop: { kind: "bars", items: [{ label: "2", value: 2 }, { label: "5", value: 5 }, { label: "8", value: 8 }, { label: "11", value: 11 }], unit: "", active: 0 }, duration: 3600 },
    { step: "步驟 2：高斯的小啟發", id: 2, caption: "小高斯算 1 加到 100 時，不是一個一個加，而是把頭尾配對：1＋100、2＋99… 每一對都是 101——找規律比硬加快多了。", action: "point", prop: { kind: "text", text: "1＋100 ＝ 2＋99 ＝ … ＝ 101", sub: "頭尾配對，規律現形", tone: "ok" }, duration: 3800 },
    { step: "步驟 3：等差的一般項", id: 3, caption: "等差數列首項 a₁、公差 d：第 n 項是 a₁ ＋（n − 1）d。第 10 項就是首項再加 9 次公差。", action: "point", prop: { kind: "text", text: "aₙ ＝ a₁ ＋（n − 1）d", sub: "2, 5, 8, 11…的 a₁ ＝ 2、d ＝ 3", tone: "ok" }, duration: 3600 },
    { step: "步驟 4：等差的和", id: 4, caption: "等差級數用「頭尾配對」：首項加末項、乘項數、再除以 2。1 加到 100 就是這樣算出來的。", ask: { prompt: "等差數列 1, 2, 3, …, 100 的總和是多少？", options: ["5050", "5000", "10100", "4950"], answer: 0, hint: "（首項 ＋ 末項）× 項數 ÷ 2。" }, action: "think", prop: { kind: "text", text: "Sₙ ＝ n（a₁ ＋ aₙ）÷ 2", sub: "（1 ＋ 100）× 100 ÷ 2 ＝ 5050", tone: "ok" }, duration: 3800 },
    { step: "步驟 5：等比的一般項", id: 5, caption: "等比數列首項 a₁、公比 r：第 n 項是 a₁ × r^(n−1)，每一項都是前一項乘 r。", action: "walk", prop: { kind: "text", text: "aₙ ＝ a₁ × r^(n−1)", sub: "1, 2, 4, 8…的 r ＝ 2", tone: "ok" }, duration: 3600 },
    { step: "步驟 6：等比求和為何長那樣", id: 6, caption: "等比求和公式不是背的：把 S 乘上 r 再和原式錯位相減，中間一大票項全消掉，只剩頭尾兩項，就化出 Sₙ 公式。", action: "point", prop: { kind: "flow", steps: ["寫出 S", "S×r 錯位", "相減消去中間項"], active: 2 }, duration: 3800 },
    { step: "步驟 7：等比的和與收斂", id: 7, caption: "等比級數的和 Sₙ ＝ a₁（rⁿ − 1）/（r − 1）；當 |r| ＜ 1，n 越大 rⁿ 越接近 0，總和會收斂。", ask: { prompt: "無窮等比數列 1 ＋ 1/2 ＋ 1/4 ＋ … 的總和是多少？", options: ["1", "1.5", "2", "無限大"], answer: 2, hint: "a₁/（1 − r），這裡 a₁ ＝ 1、r ＝ 1/2。" }, action: "jump", prop: { kind: "text", text: "|r| ＜ 1 → 和收斂到 a₁ ÷（1 − r）", sub: "1 ÷（1 − 1/2）＝ 2", tone: "ok" }, duration: 3800 },
    { step: "步驟 8：常見的錯", id: 8, caption: "常見錯誤：把 n 當成 n − 1、公比用減的、|r| ＞ 1 還套收斂公式。公式的條件要看清楚。", action: "point", prop: { kind: "text", text: "第 n 項 → 乘了 n − 1 次，不是 n 次", sub: "收斂公式只在 |r| ＜ 1 時可用", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：先問收斂再套公式", id: 9, caption: "看到「無窮」先檢查 |r| 是否小於 1：2 ＋ 1 ＋ 1/2 ＋ … 的 r ＝ 1/2 合格，和 ＝ 2 ÷（1 − 1/2）＝ 4。", ask: { prompt: "無窮等比 2 ＋ 1 ＋ 1/2 ＋ … 的總和是多少？", options: ["3", "4", "發散到無限大", "1"], answer: 1, hint: "a₁＝2、r＝1/2，和 ＝ 2 ÷（1 − 1/2）。" }, action: "think", prop: { kind: "text", text: "和 ＝ 2 ÷（1 − 1/2）＝ 4", sub: "|r|＝1/2 ＜ 1，可收斂", tone: "ok" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：先判斷「加」還是「乘」，再套一般項；求和先問「有沒有收斂」。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-sequence-1", prompt: "等差數列 3, 7, 11, …的第 10 項是多少？", options: ["39", "43", "40", "37"], answer: 0, hints: ["首項 3、公差 4", "a₁₀ ＝ 3 ＋（10 − 1）× 4"], explanation: "a₁₀ ＝ 3 ＋ 9×4 ＝ 39。" },
    { id: "sh-math-sequence-2", prompt: "等差數列 2, 4, 6, …, 20 的總和是多少？", options: ["100", "110", "120", "90"], answer: 1, hints: ["共有 10 項", "（2 ＋ 20）× 10 ÷ 2"], explanation: "S ＝（2 ＋ 20）× 10 ÷ 2 ＝ 110。" },
    { id: "sh-math-sequence-3", prompt: "等比數列 2, 6, 18, … 的公比是多少？", options: ["3", "4", "6", "1/3"], answer: 0, hints: ["公比是「後項除以本項」", "6 ÷ 2 ＝ ?"], explanation: "6 ÷ 2 ＝ 3，且 18 ÷ 6 ＝ 3，公比為 3。" },
    { id: "sh-math-sequence-4", prompt: "無窮等比級數 8 ＋ 4 ＋ 2 ＋ … 的總和是多少？", options: ["14", "15", "16", "無限大"], answer: 2, hints: ["a₁ ＝ 8、r ＝ 1/2", "和 ＝ a₁ ÷（1 − r）"], explanation: "8 ÷（1 − 1/2）＝ 16。" },
    { id: "sh-math-sequence-5", prompt: "下列哪一個等比級數的「和」會收斂？", options: ["公比 2", "公比 −1.5", "公比 1/3", "公比 1"], answer: 2, hints: ["收斂條件是公比的絕對值小於 1", "1/3 的絕對值小於 1"], explanation: "只有 |r| ＜ 1 時無窮等比級數才會收斂，1/3 符合。" },
    { id: "sh-math-sequence-6", prompt: "等差數列 5, 9, 13, … 的第 8 項是多少？", options: ["33", "37", "32", "29"], answer: 0, hints: ["首項 5、公差 4", "a₈ ＝ 5 ＋（8 − 1）× 4"], explanation: "a₈ ＝ 5 ＋ 7×4 ＝ 33。" },
    { id: "sh-math-sequence-7", prompt: "無窮等比 6 − 2 ＋ 2/3 − …（公比 −1/3）的總和是？", options: ["4.5", "3", "發散到無限大", "8"], answer: 0, hints: ["|r| ＝ 1/3 ＜ 1，可收斂", "和 ＝ 6 ÷（1 −（−1/3））＝ 6 ÷ 4/3"], explanation: "|−1/3|＜1 故收斂，和 ＝ 6 ÷（4/3）＝ 4.5；公比為負只是交錯，不影響收斂。" },
  ],
};

const SH_MATH_PERMUTATION: OnionLesson = {
  id: "sh-math-permutation",
  title: "排列組合：先問「順序要不要緊」",
  subject: "數學",
  topic: "排列與組合",
  grade: "高二",
  stages: ["高中"],
  desc: "排隊拍照要看順序（排列），選便當菜色不看順序（組合）。分清楚，就不會多算。",
  takeaways: ["乘法原理：做一件事分階段，方法數相乘", "排列 P：順序不同算不同", "組合 C：只看選了什麼，不看順序", "排列數＝組合數×選出人數的階乘；先判能否重複選、再判順序是否重要"],
  frames: [
    { step: "步驟 1：先問順序要不要緊", id: 1, caption: "嗨！同樣是「從 5 個人裡挑 2 個」：如果是排隊拍照（有順序）跟選兩個代表（沒順序），答案不一樣。", action: "wave", prop: { kind: "flow", steps: ["挑出來", "要不要排順序？"], active: 1 }, duration: 3400 },
    { step: "步驟 2：到處都在數方法數", id: 2, caption: "選課表怎麼排、密碼有幾種組合、樂透中獎率，背後都是排列組合——先會分類，才不會重複或漏掉。", action: "point", prop: { kind: "text", text: "排課、密碼、樂透、選代表", sub: "本質都是在數「有幾種方法」", tone: "ok" }, duration: 3600 },
    { step: "步驟 3：乘法原理", id: 3, caption: "如果你有 3 件上衣、4 件褲子，搭配方法就是 3 × 4 ＝ 12 種：分階段做事，方法數相乘。", action: "point", prop: { kind: "text", text: "3 件上衣 × 4 件褲子 ＝ 12 種搭配", sub: "分階段 → 相乘", tone: "ok" }, duration: 3600 },
    { step: "步驟 4：先確認能不能重複選", id: 4, caption: "動手數之前先問一件事：能不能重複選同一個？密碼可以重複數字，但選人當代表不能重複——這決定用乘法還是排列。", action: "walk", prop: { kind: "text", text: "密碼可重複；選人不可重複", sub: "可重複→每步選項都一樣多", tone: "ok" }, duration: 3600 },
    { step: "步驟 5：排列要看順序", id: 5, caption: "從 5 個人選 2 個排隊：第一個位置有 5 種、第二個位置剩 4 種，所以是 5 × 4 ＝ 20 種。", ask: { prompt: "從 5 個人中選 2 個人排成一列，共有幾種排法？", options: ["10", "20", "25", "5"], answer: 1, hint: "第一個位置 5 種、第二個位置 4 種，相乘。" }, action: "think", prop: { kind: "text", text: "5 × 4 ＝ 20 種", sub: "順序不同算不同（排列）", tone: "ok" }, duration: 3600 },
    { step: "步驟 6：組合不看順序", id: 6, caption: "如果只是選出 2 個人當代表，甲先乙後和乙先甲後是同一組，要把重複除掉：20 ÷ 2 ＝ 10 種。", action: "walk", prop: { kind: "balance", left: "排列 20 種", right: "組合 10 種", tip: "選出的每一組都被算過 2 次，所以要除以 2" }, duration: 3800 },
    { step: "步驟 7：公式寫下來", id: 7, caption: "排列 P(5, 2) ＝ 5 × 4；組合 C(5, 2) ＝ 5 × 4 ÷ 2。分母就是「選出來那幾個人的排列數」。", ask: { prompt: "從 6 個人中選 3 個人當代表（不排序），共有幾種選法？", options: ["120", "20", "18", "216"], answer: 1, hint: "C(6,3) ＝ 6×5×4 ÷（3×2×1）。" }, action: "jump", prop: { kind: "text", text: "C(5, 2) ＝ (5 × 4) ÷ (2 × 1) ＝ 10", sub: "分子是排列、分母是重複次數", tone: "ok" }, duration: 3800 },
    { step: "步驟 8：常見的錯", id: 8, caption: "常見錯誤：該用組合卻用排列（答案多了好幾倍）、忘了「不能重複選同一個人」、分類時漏掉情況。", action: "point", prop: { kind: "text", text: "先問：順序不同算不同嗎？", sub: "是 → 排列；否 → 組合", tone: "warn" }, duration: 3400 },
    { step: "步驟 9：排列是組合乘階乘", id: 9, caption: "把兩個公式連起來看：選出的一組人可以再排成幾種次序，所以排列數＝組合數×選出人數的階乘。", ask: { prompt: "從 5 人選 2 人，排列數比組合數多幾倍？", options: ["2 倍", "3 倍", "5 倍", "兩者相同"], answer: 0, hint: "選出的 2 人可排成 2!＝2 種，故排列數 ＝ 組合數 × 2。" }, action: "think", prop: { kind: "text", text: "P(5,2) ＝ 20、C(5,2) ＝ 10", sub: "差 2! ＝ 2 倍", tone: "ok" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：分階段用乘法；看順序用排列、不看順序用組合。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-permutation-1", prompt: "從 4 個不同的球中選 2 個排成一列，共有幾種排法？", options: ["6", "8", "12", "16"], answer: 2, hints: ["第一個位置 4 種", "第二個位置剩 3 種"], explanation: "4 × 3 ＝ 12 種（排列，順序有意義）。" },
    { id: "sh-math-permutation-2", prompt: "從 4 個不同的球中任選 2 個（不看順序），共有幾種選法？", options: ["4", "6", "8", "12"], answer: 1, hints: ["組合 ＝ 排列 ÷ 重複次數", "12 ÷ 2 ＝ ?"], explanation: "C(4,2) ＝ 12 ÷ 2 ＝ 6 種。" },
    { id: "sh-math-permutation-3", prompt: "早餐店有 3 種飲料、5 種主食，各選一種的搭配共有幾種？", options: ["8", "12", "15", "20"], answer: 2, hints: ["飲料與主食是兩個階段", "階段之間用乘法"], explanation: "3 × 5 ＝ 15 種（乘法原理）。" },
    { id: "sh-math-permutation-4", prompt: "下列哪一種情境適合用「組合」計算？", options: ["4 個人排隊照相", "從 8 個隊員中選 5 個上場（不分位置）", "3 位數的密碼排列", "比賽的名次順序"], answer: 1, hints: ["組合是「只看選了誰」", "不分位置表示順序不要緊"], explanation: "只選人不分位置，順序不要緊，用組合 C。" },
    { id: "sh-math-permutation-5", prompt: "C(6, 2) 等於多少？", options: ["30", "15", "12", "36"], answer: 1, hints: ["分子 6 × 5", "分母 2 × 1"], explanation: "C(6,2) ＝（6 × 5）÷（2 × 1）＝ 15。" },
    { id: "sh-math-permutation-6", prompt: "5 本不同的書排成一排，共有幾種排法？", options: ["120", "25", "60", "20"], answer: 0, hints: ["5 個位置全排列", "5 × 4 × 3 × 2 × 1"], explanation: "5 本全排即 5! ＝ 5×4×3×2×1 ＝ 120 種。" },
    { id: "sh-math-permutation-7", prompt: "從 4 男 3 女中選出 1 男 1 女當代表，共有幾種選法？", options: ["12", "7", "4", "3"], answer: 0, hints: ["選男生有 4 種、選女生有 3 種", "兩個階段用乘法"], explanation: "乘法原理：4 × 3 ＝ 12 種。" },
  ],
};

const SH_MATH_PROBABILITY: OnionLesson = {
  id: "sh-math-probability",
  title: "機率與統計：用數字描述不確定",
  subject: "數學",
  topic: "機率與統計",
  grade: "高二",
  stages: ["高中"],
  desc: "機率是「長期下來會發生的比例」，期望值是「平均會拿到的數」。算清楚，做決定就有依據。",
  takeaways: ["機率 ＝ 符合條件的情形 ÷ 全部可能情形", "獨立事件：P(A∩B) ＝ P(A) × P(B)", "期望值 ＝ 每個結果 × 它的機率，再加總", "機率必在 0 到 1 之間；互斥事件用加法、獨立事件用乘法"],
  frames: [
    { step: "步驟 1：機率在算什麼", id: 1, caption: "嗨！擲一顆公正骰子，「出現 3 的機率」是 1/6：6 種可能裡只有 1 種符合。", action: "wave", prop: { kind: "text", text: "P ＝ 符合的情形 ÷ 全部情形", sub: "骰子出現 3：1 ÷ 6 ＝ 1/6", tone: "ok" }, duration: 3600 },
    { step: "步驟 2：為什麼要學機率", id: 2, caption: "保險費率、醫療篩檢的誤判、抽獎划算不划算，都是在算「長期下來會怎樣」——這正是機率在回答的問題。", action: "point", prop: { kind: "text", text: "保險、篩檢、抽獎決策", sub: "用長期比例做判斷", tone: "ok" }, duration: 3600 },
    { step: "步驟 3：列出所有可能", id: 3, caption: "比較複雜的題目要先「不重不漏」地把情形列出來，樹狀圖或表格都好用。", action: "point", prop: { kind: "flow", steps: ["列舉所有結果", "數出符合的", "相除得機率"], active: 0 }, duration: 3400 },
    { step: "步驟 4：兩顆骰子一起擲", id: 4, caption: "兩顆骰子共有 36 種結果；點數和是 7 的有 6 種，所以機率是 6/36 ＝ 1/6。", ask: { prompt: "同時擲兩顆公正骰子，點數和為 7 的機率是多少？", options: ["1/6", "1/12", "1/36", "6/12"], answer: 0, hint: "全部 36 種，和為 7 的情形有 6 種。" }, action: "think", prop: { kind: "text", text: "6 ÷ 36 ＝ 1/6", sub: "和為 7 的組合共有 6 種", tone: "ok" }, duration: 3800 },
    { step: "步驟 5：獨立事件相乘", id: 5, caption: "兩件事互不影響時，一起發生的機率是相乘：擲到 6 且擲到 6 的機率是 1/6 × 1/6 ＝ 1/36。", action: "walk", prop: { kind: "balance", left: "1/6 × 1/6", right: "1/36", tip: "獨立事件：同時發生 = 機率相乘" }, duration: 3600 },
    { step: "步驟 6：互斥用加法、獨立用乘法", id: 6, caption: "別把兩條規則搞混：兩事件「互斥」（不會同時發生）用加法、兩事件「獨立」用乘法。一張表分清楚。", action: "point", prop: { kind: "text", text: "互斥 → P(A∪B) ＝ P(A)＋P(B)", sub: "獨立 → P(A∩B) ＝ P(A)×P(B)", tone: "ok" }, duration: 3800 },
    { step: "步驟 7：期望值", id: 7, caption: "期望值是「平均會拿到多少」：把每個結果乘上它的機率再加起來。擲骰子的期望值是 3.5。", ask: { prompt: "擲一顆公正骰子，點數的期望值是多少？", options: ["3", "3.5", "4", "6"], answer: 1, hint: "（1 ＋ 2 ＋ 3 ＋ 4 ＋ 5 ＋ 6）÷ 6。" }, action: "jump", prop: { kind: "text", text: "期望值 ＝ Σ（結果 × 機率）", sub: "（1＋2＋3＋4＋5＋6）÷ 6 ＝ 3.5", tone: "ok" }, duration: 3800 },
    { step: "步驟 8：統計量怎麼選", id: 8, caption: "平均數受極端值影響大，中位數看中間、眾數看最常出現。資料有極端值時，中位數更可靠。", action: "point", prop: { kind: "bars", items: [{ label: "平均", value: 42 }, { label: "中位數", value: 30 }, { label: "眾數", value: 25 }], unit: "分", active: 0 }, duration: 3800 },
    { step: "步驟 9：機率一定介於 0 與 1", id: 9, caption: "檢查答案靠不靠譜：不可能事件機率是 0、必然事件是 1，任何機率都不會跑出 0 到 1 這個範圍。", ask: { prompt: "某事件的機率，下列哪個數「不可能」出現？", options: ["0", "0.5", "1", "1.5"], answer: 3, hint: "機率的範圍是 0 到 1（含）。" }, action: "think", prop: { kind: "text", text: "0 ≤ 機率 ≤ 1", sub: "小於 0 或大於 1 都不合理", tone: "warn" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：機率先把情形數清楚；獨立事件相乘；期望值就是加權平均。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-probability-1", prompt: "擲一顆公正骰子，出現偶數的機率是多少？", options: ["1/6", "1/3", "1/2", "2/3"], answer: 2, hints: ["偶數有 2、4、6", "3 ÷ 6 ＝ ?"], explanation: "偶數有 3 種，機率是 3/6 ＝ 1/2。" },
    { id: "sh-math-probability-2", prompt: "同時擲兩顆公正骰子，兩顆都是 6 的機率是多少？", options: ["1/6", "1/12", "1/36", "2/36"], answer: 2, hints: ["兩顆骰子互不影響（獨立）", "1/6 × 1/6"], explanation: "獨立事件相乘：1/6 × 1/6 ＝ 1/36。" },
    { id: "sh-math-probability-3", prompt: "擲一顆公正骰子，點數的期望值是多少？", options: ["3", "3.5", "4", "6"], answer: 1, hints: ["每個點數機率都是 1/6", "（1 ＋ 2 ＋ 3 ＋ 4 ＋ 5 ＋ 6）÷ 6"], explanation: "期望值 ＝ 21 ÷ 6 ＝ 3.5。" },
    { id: "sh-math-probability-4", prompt: "一組資料是 10, 12, 13, 14, 100。哪一個統計量最能代表「典型的值」？", options: ["平均數，因為它用到所有資料", "中位數，因為極端值 100 會拉高平均", "眾數", "全距"], answer: 1, hints: ["100 是明顯的極端值", "哪個統計量不會被極端值拉走？"], explanation: "有極端值時，中位數（13）比平均數（29.8）更能代表典型值。" },
    { id: "sh-math-probability-5", prompt: "一個抽獎活動有 1/100 的機率得到 1000 元，其他情況拿 0 元，期望獎金是多少？", options: ["1 元", "10 元", "100 元", "1000 元"], answer: 1, hints: ["期望值 ＝ 結果 × 機率", "1000 × 1/100"], explanation: "期望獎金 ＝ 1000 × 1/100 ＝ 10 元。" },
    { id: "sh-math-probability-6", prompt: "袋中有 3 紅 2 白球，任取一球是紅球的機率？", options: ["3/5", "2/5", "1/2", "3/2"], answer: 0, hints: ["紅球 3 個、全部 5 個", "3 ÷ 5 等於多少"], explanation: "P(紅) ＝ 符合數 ÷ 總數 ＝ 3 ÷ 5 ＝ 3/5。" },
    { id: "sh-math-probability-7", prompt: "擲一枚公正硬幣三次，三次都出現正面的機率是？", options: ["1/8", "1/2", "1/4", "3/8"], answer: 0, hints: ["每次正面機率 1/2", "獨立事件相乘：(1/2)³"], explanation: "三次獨立事件相乘：(1/2)×(1/2)×(1/2) ＝ 1/8。" },
  ],
};

const SH_MATH_MATRIX: OnionLesson = {
  id: "sh-math-matrix",
  title: "矩陣：把資料排成表格",
  subject: "數學",
  topic: "矩陣",
  grade: "高三",
  stages: ["高中"],
  desc: "矩陣只是「有規則的數字表格」。看懂列與行，就能一次處理很多筆資料與線性關係。",
  takeaways: ["矩陣用（列 × 行）表示大小，如 2×3 是 2 列 3 行", "矩陣相加：同位置相加，大小必須相同", "矩陣相乘：左邊的行數要等於右邊的列數", "只有方陣才談反矩陣；單位矩陣乘同型矩陣等於原矩陣，乘法不交換"],
  frames: [
    { step: "步驟 1：矩陣就是表格", id: 1, caption: "嗨！矩陣是把數字排成列與行的表格，例如 2 列 3 行的矩陣，用 2 × 3 表示它的大小。", action: "wave", prop: { kind: "text", text: "2 × 3 矩陣：2 列、3 行", sub: "先講列、再講行", tone: "ok" }, duration: 3400 },
    { step: "步驟 2：矩陣為什麼好用", id: 2, caption: "全班成績表、圖像旋轉、機器人路徑，都能寫成矩陣一次處理——它讓「一整批資料」可以像一個數字那樣運算。", action: "point", prop: { kind: "text", text: "成績表、圖形旋轉、路徑運算", sub: "把一批資料當一個整體處理", tone: "ok" }, duration: 3600 },
    { step: "步驟 3：加法對位置", id: 3, caption: "矩陣相加就是把同一個位置的數字相加，所以兩個矩陣的大小必須一樣。", action: "point", prop: { kind: "flow", steps: ["大小要相同", "同位置相加", "得到新矩陣"], active: 1 }, duration: 3400 },
    { step: "步驟 4：乘法看行列", id: 4, caption: "矩陣相乘有條件：左邊的行數必須等於右邊的列數；結果的大小是「左列 × 右行」。", ask: { prompt: "（2 × 3）矩陣可以跟哪一個矩陣相乘？", options: ["2 × 3", "3 × 4", "2 × 4", "4 × 2"], answer: 1, hint: "左邊的行數（3）要等於右邊的列數。" }, action: "think", prop: { kind: "text", text: "左邊行數 ＝ 右邊列數", sub: "（2×3）×（3×4）→ 結果 2×4", tone: "ok" }, duration: 3800 },
    { step: "步驟 5：乘法的算法", id: 5, caption: "結果的第 i 列第 j 行，是左矩陣第 i 列與右矩陣第 j 行「對應相乘再加總」。", action: "walk", prop: { kind: "flow", steps: ["取左的一列", "取右的一行", "對應相乘加總"], active: 2 }, duration: 3600 },
    { step: "步驟 6：實際算一格就懂", id: 6, caption: "算一格試試：左矩陣第 1 列 [1, 2]、右矩陣第 1 行 [3, 4]，交叉點 ＝ 1×3 ＋ 2×4 ＝ 11。每一格都這樣算。", action: "point", prop: { kind: "text", text: "1×3 ＋ 2×4 ＝ 11", sub: "一列對一行，逐項相乘再加", tone: "ok" }, duration: 3800 },
    { step: "步驟 7：矩陣解方程組", id: 7, caption: "線性方程組可以寫成矩陣相乘的形式，用高斯消去法把係數整理成簡單的樣子就能解。", ask: { prompt: "高斯消去法的目的是什麼？", options: ["把矩陣變大", "把係數整理成容易讀出解的型式", "刪掉所有數字", "求行列式"], answer: 1, hint: "想想「消去」這兩個字的意思。" }, action: "jump", prop: { kind: "flow", steps: ["寫成增廣矩陣", "列運算化簡", "讀出解"], active: 1 }, duration: 3800 },
    { step: "步驟 8：常見的錯", id: 8, caption: "常見錯誤：大小不同還想相加、矩陣相乘順序顛倒（AB 與 BA 不一定相等）、點積時對錯位置。", action: "point", prop: { kind: "text", text: "矩陣相乘「不能」交換順序", sub: "AB 不一定等於 BA", tone: "warn" }, duration: 3600 },
    { step: "步驟 9：哪種矩陣才有反矩陣", id: 9, caption: "想對矩陣做「除法」（乘反矩陣），前提是它是方陣：列數等於行數。長方形矩陣沒有反矩陣。", ask: { prompt: "哪一種矩陣才可能有反矩陣（可做除法）？", options: ["方形矩陣", "長方形矩陣", "任何大小的矩陣", "全部元素為 0 的矩陣"], answer: 0, hint: "只有方陣（列數＝行數）才談反矩陣。" }, action: "think", prop: { kind: "text", text: "方陣：列數 ＝ 行數", sub: "才可能有反矩陣", tone: "ok" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：先看大小能不能算、乘法看行列對位、一次處理一整組資料就是矩陣的價值。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-matrix-1", prompt: "一個 3 × 4 的矩陣有幾列、幾行？", options: ["3 列 4 行", "4 列 3 行", "12 列", "7 行"], answer: 0, hints: ["（列 × 行）", "前面那個數字是列數"], explanation: "3 × 4 表示 3 列 4 行。" },
    { id: "sh-math-matrix-2", prompt: "（2 × 3）矩陣與（3 × 5）矩陣相乘後，結果的大小是？", options: ["2 × 3", "3 × 5", "2 × 5", "不能相乘"], answer: 2, hints: ["左邊行數 3 ＝ 右邊列數 3，可以相乘", "結果是「左列 × 右行」"], explanation: "可以相乘，結果為 2 × 5 矩陣。" },
    { id: "sh-math-matrix-3", prompt: "矩陣相加的前提是什麼？", options: ["大小必須相同", "行數相加等於列數", "必須是方陣", "沒有條件"], answer: 0, hints: ["加法是「同位置相加」", "位置對不上就沒辦法相加"], explanation: "矩陣相加要求兩個矩陣大小相同。" },
    { id: "sh-math-matrix-4", prompt: "關於矩陣乘法 AB 與 BA，下列敘述何者正確？", options: ["一定相等", "不一定相等，甚至可能無法相乘", "一定不相等", "只看數字大小決定"], answer: 1, hints: ["乘法的順序會影響能不能算", "矩陣乘法不滿足交換律"], explanation: "矩陣乘法不滿足交換律：AB 與 BA 不一定相等，甚至大小條件可能不成立。" },
    { id: "sh-math-matrix-5", prompt: "把線性方程組寫成矩陣後，高斯消去法主要在做什麼？", options: ["把矩陣轉置", "做列運算把係數化簡，方便讀出解", "計算行列式", "把矩陣變大"], answer: 1, hints: ["重點在「消去」未知數", "把係數整理成容易讀的形式"], explanation: "高斯消去法用列運算把增廣矩陣化簡，讓解一目了然。" },
    { id: "sh-math-matrix-6", prompt: "A 是 2×3、B 是 3×4，則 AB 相乘後的大小是？", options: ["2×4", "3×3", "4×2", "不能相乘"], answer: 0, hints: ["左邊行數 3 ＝ 右邊列數 3，可以相乘", "結果是「左列 × 右行」"], explanation: "左邊行數 3 ＝ 右邊列數 3 可乘，結果為 2×4 矩陣。" },
    { id: "sh-math-matrix-7", prompt: "關於矩陣，下列何者正確？", options: ["AB 一定等於 BA", "單位矩陣乘同型矩陣等於原矩陣", "矩陣相加不必看大小", "矩陣乘法滿足交換律"], answer: 1, hints: ["單位矩陣類似數字裡的 1", "矩陣乘法不滿足交換律"], explanation: "單位矩陣類似乘法單位元，乘上去不改變；AB 不一定等於 BA，相加要求大小相同。" },
  ],
};

const SH_MATH_VECTOR: OnionLesson = {
  id: "sh-math-vector",
  title: "向量：有方向的量",
  subject: "數學",
  topic: "向量與內積",
  grade: "高三",
  stages: ["高中"],
  desc: "向量同時有「大小」與「方向」。內積可以算出夾角、判斷垂直，是空間問題的萬用工具。",
  takeaways: ["向量寫成（x, y）；長度 ＝ √（x² ＋ y²）", "內積 a·b ＝ |a||b|cosθ ＝ x₁x₂ ＋ y₁y₂", "內積為 0 ⟺ 兩向量垂直", "內積正負看夾角：0 垂直、正銳角、負鈍角；向量加法是分量相加"],
  frames: [
    { step: "步驟 1：向量比純量多一個方向", id: 1, caption: "嗨！「往東走 3 公里」和「走 3 公里」不一樣，前者有方向，這就是向量。", action: "wave", prop: { kind: "text", text: "向量 ＝ 大小 ＋ 方向", sub: "（3, 4）表示往右 3、往上 4", tone: "ok" }, duration: 3400 },
    { step: "步驟 2：哪些量是向量", id: 2, caption: "力、速度、位移都同時有大小和方向，所以都是向量；只有大小沒有方向的（如質量、溫度）叫純量。", action: "point", prop: { kind: "text", text: "力、速度、位移 ＝ 向量", sub: "質量、溫度 ＝ 純量", tone: "ok" }, duration: 3600 },
    { step: "步驟 3：長度怎麼算", id: 3, caption: "向量（3, 4）的長度是 5，因為 √（3² ＋ 4²） ＝ √25 ＝ 5——其實就是畢氏定理。", action: "point", prop: { kind: "shape", shape: "triangle", base: 3, height: 4, label: "向量（3, 4）長度 ＝ 5" }, duration: 3600 },
    { step: "步驟 4：內積有兩種算法", id: 4, caption: "內積可以用座標算（x 乘 x、y 乘 y 再加），也可以用長度與夾角算：|a||b|cosθ。", ask: { prompt: "向量 a ＝（1, 2）、b ＝（3, 4），a·b 等於多少？", options: ["7", "10", "11", "14"], answer: 2, hint: "1×3 ＋ 2×4。" }, action: "think", prop: { kind: "text", text: "a·b ＝ x₁x₂ ＋ y₁y₂", sub: "（1, 2）·（3, 4）＝ 3 ＋ 8 ＝ 11", tone: "ok" }, duration: 3800 },
    { step: "步驟 5：內積判斷垂直", id: 5, caption: "兩向量垂直時夾角 90°，cos90° ＝ 0，所以內積等於 0。反過來內積為 0 也代表垂直。", action: "walk", prop: { kind: "balance", left: "a·b ＝ 0", right: "兩向量垂直", tip: "cos90° ＝ 0" }, duration: 3600 },
    { step: "步驟 6：向量相加分量對分量", id: 6, caption: "向量相加很單純：x 加 x、y 加 y。（3, 4）＋（1, −1）＝（4, 3），也就是頭尾相接後的總位移。", action: "point", prop: { kind: "text", text: "（3, 4）＋（1, −1）＝（4, 3）", sub: "分量對分量相加", tone: "ok" }, duration: 3600 },
    { step: "步驟 7：算夾角", id: 7, caption: "要求夾角，就把內積除以兩個長度的乘積，得到 cosθ 再反推角度。", ask: { prompt: "a·b ＝ 6、|a| ＝ 2、|b| ＝ 3，則兩向量的夾角是？", options: ["0°", "30°", "60°", "90°"], answer: 0, hint: "cosθ ＝ 6 ÷（2 × 3）＝ 1，代表同方向。" }, action: "jump", prop: { kind: "text", text: "cosθ ＝（a·b）÷（|a||b|）", sub: "6 ÷ 6 ＝ 1 → θ ＝ 0°", tone: "ok" }, duration: 3800 },
    { step: "步驟 8：常見的錯", id: 8, caption: "常見錯誤：把內積當成向量（內積結果是一個數）、忘了先檢查垂直、長度計算漏平方。", action: "point", prop: { kind: "text", text: "內積的結果是一個「數」", sub: "不是向量，也不能拿來當方向", tone: "warn" }, duration: 3400 },
    { step: "步驟 9：內積正負看夾角", id: 9, caption: "把內積讀成夾角訊號：等於 0 是直角、為正是銳角（小於 90°）、為負是鈍角（大於 90°）。", ask: { prompt: "若 a·b ＝ |a||b|，則兩向量的關係是？", options: ["互相垂直", "同向平行", "反向平行", "夾 45°"], answer: 1, hint: "cosθ ＝ 1，代表 θ ＝ 0°，方向完全相同。" }, action: "think", prop: { kind: "text", text: "cosθ ＝ 1 → 同向平行", sub: "cosθ ＝ −1 → 反向平行", tone: "ok" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：向量看座標就對了；內積算座標最快，要判斷垂直只看內積是否為 0。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-vector-1", prompt: "向量（6, 8）的長度是多少？", options: ["10", "14", "48", "100"], answer: 0, hints: ["長度 ＝ √（x² ＋ y²）", "√（36 ＋ 64）＝ ?"], explanation: "長度 ＝ √（6² ＋ 8²）＝ √100 ＝ 10。" },
    { id: "sh-math-vector-2", prompt: "a ＝（2, 3）、b ＝（4, −1），a·b 等於多少？", options: ["5", "11", "8", "3"], answer: 0, hints: ["內積 ＝ x₁x₂ ＋ y₁y₂", "2×4 ＋ 3×（−1）"], explanation: "2×4 ＋ 3×（−1）＝ 8 − 3 ＝ 5。" },
    { id: "sh-math-vector-3", prompt: "若兩向量垂直，則它們的內積是多少？", options: ["0", "1", "等於兩者長度相乘", "無法判斷"], answer: 0, hints: ["垂直代表夾角 90°", "cos90° ＝ 0"], explanation: "夾角 90° 時 cosθ ＝ 0，所以內積為 0。" },
    { id: "sh-math-vector-4", prompt: "下列哪一個向量與（3, 4）垂直？", options: ["（4, 3）", "（4, −3）", "（3, −4）", "（6, 8）"], answer: 1, hints: ["垂直的內積要為 0", "3×4 ＋ 4×（−3）＝ ?"], explanation: "（3, 4）·（4, −3）＝ 12 − 12 ＝ 0，所以垂直。" },
    { id: "sh-math-vector-5", prompt: "a·b ＝ 0、|a| ＝ 5、|b| ＝ 2，則兩向量的夾角是？", options: ["90°", "60°", "30°", "0°"], answer: 0, hints: ["cosθ ＝（a·b）÷（|a||b|）", "0 除以任何正數都是 0"], explanation: "cosθ ＝ 0 ÷ 10 ＝ 0，所以 θ ＝ 90°。" },
    { id: "sh-math-vector-6", prompt: "a ＝（3, 4）、b ＝（0, −1），則 a ＋ b 等於？", options: ["（3, 3）", "（3, 5）", "（3, −3）", "（2, 3）"], answer: 0, hints: ["分量分別相加", "（3 ＋ 0, 4 ＋（−1））"], explanation: "分量相加：（3, 4）＋（0, −1）＝（3, 3）。" },
    { id: "sh-math-vector-7", prompt: "若兩向量的內積為負，則它們的夾角為？", options: ["銳角", "直角", "鈍角", "0°"], answer: 2, hints: ["cosθ 為負", "cosθ ＜ 0 表示角度在 90° 到 180° 之間"], explanation: "內積為負表示 cosθ ＜ 0，夾角大於 90°，是鈍角。" },
  ],
};

const SH_MATH_CALCULUS: OnionLesson = {
  id: "sh-math-calculus-intro",
  title: "微積分初步：切線與面積",
  subject: "數學",
  topic: "微積分初步",
  grade: "高三",
  stages: ["高中"],
  desc: "微分求「瞬間的變化率」（切線斜率），積分求「累積的總量」（曲線下的面積），兩者互為反向操作。",
  takeaways: ["導數 f'(a) 是圖形在 x ＝ a 的切線斜率", "多項式微分：xⁿ 的導數是 n·x^(n−1)", "定積分是曲線下的面積，與微分互為反運算", "f'(a)＝0 是極值候選點，看兩側正負才分辨是山頂或谷底"],
  frames: [
    { step: "步驟 1：先問「變化多快」", id: 1, caption: "嗨！開車時儀表板上的「時速」是某一瞬間的速度，不是整趟的平均，這就需要微分。", action: "wave", prop: { kind: "text", text: "平均速度 vs 瞬間速度", sub: "瞬間的變化率就是導數", tone: "ok" }, duration: 3400 },
    { step: "步驟 2：瞬間速度是怎麼來的", id: 2, caption: "瞬間速度不是神祕的東西：把「一段時間的平均速度」那段時間越取越小，趨近 0 時的極限，就是瞬間速度。", action: "point", prop: { kind: "text", text: "Δt 越取越小 → 趨近 0", sub: "平均速度的極限 ＝ 瞬間速度", tone: "ok" }, duration: 3600 },
    { step: "步驟 3：斜率就是變化率", id: 3, caption: "在圖形上，某一點的切線斜率就是那一點的變化率：上升很陡 → 導數很大。", action: "point", prop: { kind: "flow", steps: ["取一點", "畫切線", "量斜率 ＝ 導數"], active: 2 }, duration: 3400 },
    { step: "步驟 4：多項式怎麼微分", id: 4, caption: "公式很好記：xⁿ 的導數是 n·x^(n−1)。例如 x³ 的導數是 3x²、常數的導數是 0。", ask: { prompt: "f(x) ＝ x³，則 f'(x) 等於？", options: ["x²", "3x²", "3x³", "x⁴/4"], answer: 1, hint: "把指數搬到前面，再減 1。" }, action: "think", prop: { kind: "text", text: "x³ → 3x²", sub: "指數搬到前面，指數減 1", tone: "ok" }, duration: 3600 },
    { step: "步驟 5：多項式逐項微分", id: 5, caption: "碰到多項式就逐項做：f(x) ＝ x² ＋ 3x ＋ 1，分別得 2x、3、0，合起來 f'(x) ＝ 2x ＋ 3。", action: "point", prop: { kind: "text", text: "x² ＋ 3x ＋ 1 → 2x ＋ 3", sub: "常數項的導數是 0", tone: "ok" }, duration: 3800 },
    { step: "步驟 6：導數的應用", id: 6, caption: "f'(a) 為正代表函數在上升、為負代表下降、等於 0 代表可能在山頂或谷底（極值）。", action: "walk", prop: { kind: "text", text: "f'(a) ＞ 0：上升", sub: "f'(a) ＝ 0：可能是極值", tone: "ok" }, duration: 3600 },
    { step: "步驟 7：積分求面積", id: 7, caption: "反過來，把曲線下的區域切成很多細細的長條再加起來，就是定積分——它算的是累積的總量。", ask: { prompt: "定積分在圖形上代表什麼？", options: ["切線的斜率", "曲線與 x 軸之間的面積", "函數的最大值", "資料的平均"], answer: 1, hint: "把面積切成很多細長條再加起來。" }, action: "jump", prop: { kind: "bars", items: [{ label: "細長條 1", value: 2 }, { label: "細長條 2", value: 5 }, { label: "細長條 3", value: 8 }], unit: "", active: 1 }, duration: 3800 },
    { step: "步驟 8：微分與積分互為反向", id: 8, caption: "微分是「看變化」、積分是「把變化加回來」，所以一個函數先微分再積分（在條件允許下）會回到原來的函數。", action: "point", prop: { kind: "balance", left: "微分（變化率）", right: "積分（累積量）", tip: "兩者互為反向操作" }, duration: 3800 },
    { step: "步驟 9：導數為零是極值候選", id: 9, caption: "切線水平（f'(a) ＝ 0）的點，函數可能正在轉彎：它是「極值候選」，但還要看兩側正負才知道是山頂或谷底。", ask: { prompt: "f'(a) ＝ 0 的點，最可能代表什麼？", options: ["一定是最大值", "可能是極值（山頂或谷底）", "一定是最小值", "函數值等於 0"], answer: 1, hint: "導數為 0 表示切線水平，是轉彎的候選，未必是最大或最小。" }, action: "think", prop: { kind: "text", text: "f'(a) ＝ 0 → 極值候選", sub: "看兩側正負才知山頂或谷底", tone: "ok" }, duration: 3800 },
    { step: "步驟 10：帶走這個判斷", id: 10, caption: "記住：看到「瞬時、最快、極值」想微分；看到「總量、面積、累積」想積分。準備闖關！", action: "cheer", prop: { kind: "none" }, duration: 2800 },
  ],
  questions: [
    { id: "sh-math-calculus-intro-1", prompt: "f(x) ＝ x² 的導函數 f'(x) 是？", options: ["x", "2x", "x²", "2x²"], answer: 1, hints: ["xⁿ 的導數是 n·x^(n−1)", "指數 2 搬到前面，指數減 1"], explanation: "x² 的導數是 2x^(2−1) ＝ 2x。" },
    { id: "sh-math-calculus-intro-2", prompt: "函數 f(x) ＝ 5（常數函數）的導數是？", options: ["5", "1", "0", "x"], answer: 2, hints: ["常數不會變化", "變化率為 0"], explanation: "常數函數圖形是水平線，斜率 0，所以導數為 0。" },
    { id: "sh-math-calculus-intro-3", prompt: "若 f'(3) ＞ 0，則函數在 x ＝ 3 附近？", options: ["正在上升", "正在下降", "有最大值", "是水平線"], answer: 0, hints: ["導數就是切線斜率", "斜率為正代表往上"], explanation: "導數為正表示切線斜率為正，函數在該處上升。" },
    { id: "sh-math-calculus-intro-4", prompt: "定積分在圖形上代表什麼？", options: ["切線斜率", "曲線與 x 軸之間的面積", "函數的極值", "資料的眾數"], answer: 1, hints: ["切成很多細長條加起來", "算的是累積量"], explanation: "定積分代表曲線與 x 軸之間的面積（累積量）。" },
    { id: "sh-math-calculus-intro-5", prompt: "下列哪一種問法最需要用「積分」？", options: ["求某瞬間的速度", "求圖形在某點的切線斜率", "求曲線下從 0 到 3 的面積", "求函數的最大值"], answer: 2, hints: ["積分處理「累積的總量」", "面積是典型的累積問題"], explanation: "求曲線下的面積要用定積分；切線斜率與極值屬微分。" },
    { id: "sh-math-calculus-intro-6", prompt: "f(x) ＝ x⁴，則 f'(x) 等於？", options: ["4x³", "x³", "4x⁴", "3x⁴"], answer: 0, hints: ["xⁿ 的導數是 n·x^(n−1)", "指數 4 搬到前面，再減 1"], explanation: "f'(x) ＝ 4x^(4−1) ＝ 4x³。" },
    { id: "sh-math-calculus-intro-7", prompt: "f(x) ＝ x² − 4x，在何處 f'(x) ＝ 0（極值候選）？", options: ["x ＝ 2", "x ＝ 0", "x ＝ 4", "x ＝ −2"], answer: 0, hints: ["先求 f'(x) ＝ 2x − 4", "令 2x − 4 ＝ 0"], explanation: "f'(x) ＝ 2x − 4 ＝ 0 → x ＝ 2，此處正是拋物線頂點。" },
  ],
};

export default [
  SH_MATH_POLYNOMIAL,
  SH_MATH_EXP_LOG,
  SH_MATH_TRIG,
  SH_MATH_LINE_CIRCLE,
  SH_MATH_SEQUENCE,
  SH_MATH_PERMUTATION,
  SH_MATH_PROBABILITY,
  SH_MATH_MATRIX,
  SH_MATH_VECTOR,
  SH_MATH_CALCULUS,
];
